<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Amount_inputValue</name>
   <tag></tag>
   <elementGuidId>86315777-3b6a-4a53-a6ab-57ab849d90d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputValue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputValue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>649e65f5-9c45-4380-ac4f-b5b6cd9377dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputValue</value>
      <webElementGuid>70cd4129-24ef-464a-b0db-cb8d486ef2f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cd9e2028-ac3c-4984-a843-1f8564cf8f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0,00€</value>
      <webElementGuid>dfd0a91b-3ff0-4b11-bdeb-13a35a399b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>30789006-95fd-4186-a440-2381bad11fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputValue&quot;)</value>
      <webElementGuid>b168320a-7c70-4736-9ece-5cd85faff4df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputValue']</value>
      <webElementGuid>ac2bcf5c-fbd9-4fc3-9cbc-a98b9050ed19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-router-outlet[@id='main-content']/div[4]/ion-content/div/ion-grid/ion-row[3]/ion-col/input</value>
      <webElementGuid>3cc73b59-1952-4b7e-9f9c-8a44f9900b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/following::input[1]</value>
      <webElementGuid>82aedfa2-b21d-4f8d-b2ac-475ee090a3d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send to:'])[1]/following::input[1]</value>
      <webElementGuid>135ddfad-697b-4b1b-b1ec-3bf7bacacdab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The amount must be greater than 0'])[1]/preceding::input[1]</value>
      <webElementGuid>f06c4208-80b9-4167-b00e-d9a2d4562fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send'])[1]/preceding::input[1]</value>
      <webElementGuid>76e21cf9-75de-4380-8fbd-b440b334b52a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-col/input</value>
      <webElementGuid>fbdc0a00-674d-49ed-98c4-7c2d97c1d361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputValue' and @type = 'text' and @placeholder = '0,00€']</value>
      <webElementGuid>d4ffabf7-44a4-4aec-b9a8-7ee4ed0a258d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
