<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_item-inner-0000002-285</name>
   <tag></tag>
   <elementGuidId>84647085-af1a-45de-8e82-e9df98501ee2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.item-native > div.item-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>de1f2533-0ec0-4f8e-9c8d-34aaf45e2ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-inner</value>
      <webElementGuid>988689dd-0044-4562-bf74-f0db6c05f294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/button[@class=&quot;item-native&quot;]/div[@class=&quot;item-inner&quot;]</value>
      <webElementGuid>2e2035ae-87d9-45b9-afe1-5b5fec1c855d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TP50SendMoney/ion-item-contact-vcard</value>
      <webElementGuid>899f07ec-7d27-4cc1-aab8-c5580a064ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e554632d-ef88-44be-9b06-8a5d7c9231a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>86ec4b40-0b7f-413b-bbf4-8649bd022b2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
