<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-item-contact-vcard</name>
   <tag></tag>
   <elementGuidId>3eb1f47d-97b7-4bf4-aa44-12b532da0a2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ion-router-outlet[@id='main-content']/div[3]/ion-content/div/div[2]/ion-list/ion-item-sliding[3]/ion-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-item</value>
      <webElementGuid>a4e3db14-2a81-46e7-960e-033ae6fd4951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-has-start-slot item md item-lines-default item-fill-none in-list ion-activatable ion-focusable item-label</value>
      <webElementGuid>60c8782b-733a-48a8-a34b-34556e71bd83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listitem</value>
      <webElementGuid>feeb0ed9-787e-430f-8a7f-eec19c8d7a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Miguel Pedrosa Alberto900000002</value>
      <webElementGuid>7fb513e2-d8db-448c-b1b1-8a3a6b62cbe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ion-page can-go-back&quot;]/ion-content[@class=&quot;md content-ltr&quot;]/div[1]/div[2]/ion-list[@class=&quot;md list-md list-inset&quot;]/ion-item-sliding[@class=&quot;md&quot;]/ion-item[@class=&quot;item-has-start-slot item md item-lines-default item-fill-none in-list ion-activatable ion-focusable item-label&quot;]</value>
      <webElementGuid>cedc897a-c19d-4285-b19f-f00314c36e23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-router-outlet[@id='main-content']/div[3]/ion-content/div/div[2]/ion-list/ion-item-sliding[3]/ion-item</value>
      <webElementGuid>3e754aa2-c9ff-49ea-8519-0cd6f9966475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='João Tavares'])[1]/following::ion-item[1]</value>
      <webElementGuid>a1ddfbf6-c8fb-40ea-b5df-b634486a81b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Afonso Cancela'])[1]/following::ion-item[2]</value>
      <webElementGuid>ca5793b5-f648-4efe-af22-f3f7e7fd8f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='João Miguel Antunes Carvalho da Silva'])[1]/preceding::ion-item[1]</value>
      <webElementGuid>884cdf2d-59ef-4641-8691-ec0de22209b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-item-sliding[3]/ion-item</value>
      <webElementGuid>07228398-bb3b-425a-b6d8-5984cad9da3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-item[(text() = 'Miguel Pedrosa Alberto900000002' or . = 'Miguel Pedrosa Alberto900000002')]</value>
      <webElementGuid>9da48387-64a1-486d-a6d9-a3ae8aee7211</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
