<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-content_Add New ContactAfonso Cancela91_7061e0</name>
   <tag></tag>
   <elementGuidId>7bd69608-4f3e-4913-8b9c-2a62d0893598</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ion-router-outlet[@id='main-content']/div[3]/ion-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-content</value>
      <webElementGuid>e0893b25-8efb-45f8-8e2e-729916b03ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md content-ltr</value>
      <webElementGuid>ccb5726f-5b4a-4fdc-8f9d-b4f6f03ee527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add New ContactAfonso Cancela918821097João Tavares900000001Miguel Pedrosa Alberto900000002João Miguel Antunes Carvalho da Silva900000003</value>
      <webElementGuid>15027b3f-e7b4-4549-8111-a3e99787cf06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ion-page can-go-back&quot;]/ion-content[@class=&quot;md content-ltr&quot;]</value>
      <webElementGuid>b21af05d-e5fb-487f-bd5c-94cb26a7ca60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-router-outlet[@id='main-content']/div[3]/ion-content</value>
      <webElementGuid>6ee49253-2bbe-4c3c-ac03-56be4842046f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacts'])[1]/following::ion-content[1]</value>
      <webElementGuid>74d4e2f2-b8bb-41ed-8d35-1684c4cafdb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show More'])[1]/following::ion-content[1]</value>
      <webElementGuid>df1d7db1-97cf-4145-a002-dd2ad60fcb6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ion-content</value>
      <webElementGuid>550d412f-69d5-41d4-936c-8865cc0f3f3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-content[(text() = 'Add New ContactAfonso Cancela918821097João Tavares900000001Miguel Pedrosa Alberto900000002João Miguel Antunes Carvalho da Silva900000003' or . = 'Add New ContactAfonso Cancela918821097João Tavares900000001Miguel Pedrosa Alberto900000002João Miguel Antunes Carvalho da Silva900000003')]</value>
      <webElementGuid>5df599d9-41ed-4ba9-8751-c0ecf080e817</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
