<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>main_inner-scroll scroll-y-0000003-7de</name>
   <tag></tag>
   <elementGuidId>e23ec658-3607-40dd-b6ca-a7bc96bcde65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>main.inner-scroll.scroll-y</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>111704f3-782e-4f12-93f4-f6c2f6f132ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inner-scroll scroll-y</value>
      <webElementGuid>b1d376a3-809e-47da-8b2a-79b1a244c625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>scroll</value>
      <webElementGuid>58833582-ddab-4016-b98b-5249123be304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/main[@class=&quot;inner-scroll scroll-y&quot;]</value>
      <webElementGuid>9f277f13-733a-405f-909c-df1cfba526c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TP50SendMoney/ion-content_Add New ContactAfonso Cancela91_7061e0</value>
      <webElementGuid>31f15b69-013b-4a39-80fa-c6269c04533b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e6f04327-d7d3-45eb-9404-c0707d26b80b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>c3f01441-8f1c-4baf-99d1-75fb5eadaa53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
