<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-item_ReferencePT72631171955710589063305_887fab</name>
   <tag></tag>
   <elementGuidId>c8dbfe34-1a0c-4b6c-b7a8-f0318826cdfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ion-router-outlet[@id='main-content']/div[3]/ion-content/div/div/ion-list/ion-item</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div > div > ion-list.md.list-md > ion-item.item.md.item-lines-default.item-fill-none.in-list.item-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-item</value>
      <webElementGuid>b1aac3a8-6442-4240-ad07-247a58bec79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item md item-lines-default item-fill-none in-list item-label</value>
      <webElementGuid>d0b76f20-3f4c-43da-ad5a-372f6561e938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listitem</value>
      <webElementGuid>1fc2e892-91b1-4fc3-bbe2-211974f9e4ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reference:PT726311719557105890633052023-11-16 11:49:04-17.18€</value>
      <webElementGuid>b822c792-8784-4672-ab98-4fc4a6445ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ion-page can-go-back&quot;]/ion-content[@class=&quot;md content-ltr ion-padding&quot;]/div[1]/div[1]/ion-list[@class=&quot;md list-md&quot;]/ion-item[@class=&quot;item md item-lines-default item-fill-none in-list item-label&quot;]</value>
      <webElementGuid>c0f11eba-6ce1-4423-874d-974072401f6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-router-outlet[@id='main-content']/div[3]/ion-content/div/div/ion-list/ion-item</value>
      <webElementGuid>d2268c84-06d8-4c13-86b4-60dd889e12fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transactions'])[1]/following::ion-item[1]</value>
      <webElementGuid>ab57e3e5-65be-4c2e-9f4e-6c6fe4dbc4e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show More'])[1]/following::ion-item[1]</value>
      <webElementGuid>cc71023b-9466-492e-b6d7-c923151b5c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='moura.davi@nogueira.pt'])[1]/preceding::ion-item[3]</value>
      <webElementGuid>8956e5fd-57f3-4911-a3bf-0b251b46ff52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ion-list/ion-item</value>
      <webElementGuid>2f199e78-9134-423f-8cba-a7d208939c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-item[(text() = 'Reference:PT726311719557105890633052023-11-16 11:49:04-17.18€' or . = 'Reference:PT726311719557105890633052023-11-16 11:49:04-17.18€')]</value>
      <webElementGuid>fba6822d-8620-47fe-bace-94eb7cc8a2ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
