<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-list_PhonePasswordPIN</name>
   <tag></tag>
   <elementGuidId>1fe04c7f-ffe1-4ee7-aea2-80677bc22552</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ion-router-outlet[@id='main-content']/div/ion-content/div/ion-list</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ion-list.list-container.md.list-md</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-list</value>
      <webElementGuid>be28cc9c-a50a-4b2c-8693-3e2c5bded6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-container md list-md</value>
      <webElementGuid>c30b40d6-12d0-49a4-aa35-fb5ff9c297ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>1786814e-c8ef-4f61-a726-f46b488b2953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PhonePasswordPIN</value>
      <webElementGuid>a6f430c6-1b27-44ce-b23c-2c6fde94ca37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ion-page&quot;]/ion-content[@class=&quot;ion-padding md content-ltr&quot;]/div[@class=&quot;container&quot;]/ion-list[@class=&quot;list-container md list-md&quot;]</value>
      <webElementGuid>3a9249af-7663-42b2-bcc3-02aec0d0c6da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-router-outlet[@id='main-content']/div/ion-content/div/ion-list</value>
      <webElementGuid>a20e150e-ea21-4690-bfd7-8e17e20a3ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::ion-list[1]</value>
      <webElementGuid>6c4701ab-0595-4bbf-b514-cbed698fe7f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::ion-list[1]</value>
      <webElementGuid>f0a5d4bc-2670-4913-acb2-10a2564db35c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ion-list</value>
      <webElementGuid>03ad69e0-96f0-4165-98da-f6e7f44f5ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-list[(text() = 'PhonePasswordPIN' or . = 'PhonePasswordPIN')]</value>
      <webElementGuid>0fda49de-09fc-4661-a911-671fb7fd8718</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
