<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-button_Cancel</name>
   <tag></tag>
   <elementGuidId>abeb90cd-1005-4df7-88ed-48c3388f9844</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ion-modal[@id='ion-overlay-2']/div/ion-content/ion-grid/ion-row/div[3]/ion-button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ion-button.ion-color.ion-color-dark.md.button.button-full.button-solid.ion-activatable.ion-focusable</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-button</value>
      <webElementGuid>a3fde4e1-e9ce-4903-bf70-6cf2252989ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ion-color ion-color-dark md button button-full button-solid ion-activatable ion-focusable</value>
      <webElementGuid>0808c370-30b7-4eb4-b05f-c08eb4ab9395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>dark</value>
      <webElementGuid>bb2be8bb-2bda-477a-a0d1-417e556bc04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>expand</name>
      <type>Main</type>
      <value>full</value>
      <webElementGuid>92d79da0-61ca-4d9c-886c-37e42dc9924d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>f59d0596-114e-4fd2-97a6-86fb1be878ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ion-overlay-2&quot;)/div[@class=&quot;ion-delegate-host ion-page&quot;]/ion-content[@class=&quot;ion-text-center md content-ltr&quot;]/ion-grid[@class=&quot;vertically-center-aligned md&quot;]/ion-row[@class=&quot;vertically-center-aligned md&quot;]/div[@class=&quot;w-100&quot;]/ion-button[@class=&quot;ion-color ion-color-dark md button button-full button-solid ion-activatable ion-focusable&quot;]</value>
      <webElementGuid>0e622894-30c3-4277-9b1f-7073dcfd39d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-modal[@id='ion-overlay-2']/div/ion-content/ion-grid/ion-row/div[3]/ion-button[2]</value>
      <webElementGuid>55afb0fb-357d-49b4-881e-8d42c53911fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[1]/following::ion-button[1]</value>
      <webElementGuid>2daa3bac-70b9-443c-a481-78612d8b7f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You must enter your confirmation code'])[1]/following::ion-button[2]</value>
      <webElementGuid>17fbcf98-a114-43a4-bd77-bb1d73e9812f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::ion-button[1]</value>
      <webElementGuid>4af13a46-a46d-4bac-8ac3-5d5a72479f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::ion-button[1]</value>
      <webElementGuid>45d48ef8-8e63-4977-9438-62cf919dbb3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ion-button[2]</value>
      <webElementGuid>40816627-8046-4f69-bc42-90240e5f64d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-button[(text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>5d3be4b2-bf87-4d5c-982f-90da6731cc7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
