<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-select_AllDebitCredit</name>
   <tag></tag>
   <elementGuidId>bcc8465f-bbdf-40ba-9c20-4aa5f885f210</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ion-modal[@id='ion-overlay-2']/div/ion-content/ion-list/ion-item/ion-select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ion-select.md.in-item.has-value.has-placeholder.ion-focusable.select-ltr.select-justify-space-between.select-label-placement-start</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-select</value>
      <webElementGuid>b24f9455-1834-4063-b73e-f376ddc4d61d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md in-item has-value has-placeholder ion-focusable select-ltr select-justify-space-between select-label-placement-start</value>
      <webElementGuid>782cb99f-f97e-4fbc-9222-de7c96359891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>modelvalue</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>ebe085b1-eed5-418e-bc65-a76acab0050c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AllDebitCredit</value>
      <webElementGuid>5b9180ae-de71-4e3e-86eb-a5172cd92587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ion-overlay-2&quot;)/div[@class=&quot;ion-page&quot;]/ion-content[@class=&quot;ion-padding md content-ltr&quot;]/ion-list[@class=&quot;md list-md&quot;]/ion-item[@class=&quot;item md item-lines-default item-fill-none item-has-interactive-control in-list ion-activatable ion-focusable ion-activated&quot;]/ion-select[@class=&quot;md in-item has-value has-placeholder ion-focusable select-ltr select-justify-space-between select-label-placement-start&quot;]</value>
      <webElementGuid>a604f25b-0a48-401b-a9c6-fdab87dd2aed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-modal[@id='ion-overlay-2']/div/ion-content/ion-list/ion-item/ion-select</value>
      <webElementGuid>6340570b-aed9-437b-b2e6-2f43182a6dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Date:'])[1]/following::ion-select[1]</value>
      <webElementGuid>548edaeb-ff03-48bc-b1f9-e0bc893aec5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Date:'])[1]/following::ion-select[1]</value>
      <webElementGuid>bc0248dd-8f16-4922-8538-53cfc301317d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-select</value>
      <webElementGuid>e507f988-d8bc-49c8-afa5-f14afc97dea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-select[(text() = 'AllDebitCredit' or . = 'AllDebitCredit')]</value>
      <webElementGuid>97d82d05-32ee-4736-a2bf-dfac79c1a550</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
