<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dashboardBalanceValue</name>
   <tag></tag>
   <elementGuidId>c2580050-7a94-45fb-a448-7f3c6c8fec74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ion-card-title.ion-inherit-color.md</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ion-router-outlet[@id='main-content']/div[2]/ion-content/div/div/ion-grid/ion-row[2]/ion-col/ion-card/ion-card-header/ion-card-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-card-title</value>
      <webElementGuid>668646c6-fce1-4244-9a02-4f4470d8965b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ion-inherit-color md</value>
      <webElementGuid>05ac6ee0-96d0-4e87-986e-df84e0161e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>04e253d4-a7f4-4c3c-b511-6d1b0b68279a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>376b66b4-7d02-4849-ba22-fe11b16f08db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>199,47 €</value>
      <webElementGuid>ae0f261f-18d5-4598-abcd-f5277e41a7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ion-page can-go-back&quot;]/ion-content[@class=&quot;md content-ltr&quot;]/div[1]/div[1]/ion-grid[@class=&quot;md&quot;]/ion-row[@class=&quot;md&quot;]/ion-col[@class=&quot;md&quot;]/ion-card[@class=&quot;md&quot;]/ion-card-header[@class=&quot;ion-inherit-color md&quot;]/ion-card-title[@class=&quot;ion-inherit-color md&quot;]</value>
      <webElementGuid>7b35f56a-f715-4830-be4b-94f36a7832d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-router-outlet[@id='main-content']/div[2]/ion-content/div/div/ion-grid/ion-row[2]/ion-col/ion-card/ion-card-header/ion-card-title</value>
      <webElementGuid>80568cea-34ff-4c02-b8f0-60d4cc2829f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[1]/following::ion-card-title[1]</value>
      <webElementGuid>863cfdd2-921a-4f72-8efc-0d55412468b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balance'])[1]/preceding::ion-card-title[1]</value>
      <webElementGuid>a0ef6a8a-a758-48c2-944b-71a95af34a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Piggy Bank'])[1]/preceding::ion-card-title[2]</value>
      <webElementGuid>daf6efe5-75f9-4b2d-be6b-b1e1940bcc29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='199,47 €']/parent::*</value>
      <webElementGuid>a693edca-d6f6-4f6e-8e53-b21b70d1c159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-card-title</value>
      <webElementGuid>3b0da002-92fc-4939-bcac-435775fcd8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-card-title[(text() = '199,47 €' or . = '199,47 €')]</value>
      <webElementGuid>fffec8f6-c907-47fa-859b-a086aaa908a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
