<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-button_Create</name>
   <tag></tag>
   <elementGuidId>1bf1f4a1-11c7-481a-adb4-891a66fa0627</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ion-router-outlet[@id='main-content']/div/ion-content/div/ion-button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ion-button.md.button.button-block.button-solid.ion-activatable.ion-focusable.ion-activated</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-button</value>
      <webElementGuid>e67a0a55-f630-416a-b65d-109ab9e72747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md button button-block button-solid ion-activatable ion-focusable ion-activated</value>
      <webElementGuid>90aa5a04-2f3e-42c8-b552-365b0f67c5bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>expand</name>
      <type>Main</type>
      <value>block</value>
      <webElementGuid>e48f18cf-18d3-40c0-ba50-7d574f6919e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>cc3253e4-3559-4a09-ab59-7526d5f9d9c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ion-page&quot;]/ion-content[@class=&quot;ion-padding md content-ltr&quot;]/div[@class=&quot;container&quot;]/ion-button[@class=&quot;md button button-block button-solid ion-activatable ion-focusable ion-activated&quot;]</value>
      <webElementGuid>cbbbac02-2f48-4d86-b5f3-218f72885226</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-router-outlet[@id='main-content']/div/ion-content/div/ion-button</value>
      <webElementGuid>474d971c-c9e7-4bfa-8d75-d4a262c82bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PIN'])[1]/following::ion-button[1]</value>
      <webElementGuid>6366c371-b394-42f0-bd55-938fc8bc011f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::ion-button[1]</value>
      <webElementGuid>2f1f1611-588f-4448-9130-29329756f4b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-button</value>
      <webElementGuid>c84ad23e-5fb8-4ee3-a952-fb6bbd10aa88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-button[(text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>a086d3fe-5737-4e96-8e8d-7727281fc2b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
