<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_0.99 saved to your Piggy Bank Vault</name>
   <tag></tag>
   <elementGuidId>e06fe59e-68b7-4419-93a6-2a249e5c1db9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ion-modal[@id='ion-overlay-2']/div/ion-content/ion-grid/ion-row/div/ion-card/ion-card-content/p[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c8b5674e-6835-41eb-a973-8c8e9d18e901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0.99€ saved to your Piggy Bank Vault</value>
      <webElementGuid>d6102625-0707-49fd-ad0f-3cd9b41192ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ion-overlay-2&quot;)/div[@class=&quot;ion-delegate-host ion-page&quot;]/ion-content[@class=&quot;ion-text-center md content-ltr&quot;]/ion-grid[@class=&quot;md vertically-center-aligned&quot;]/ion-row[@class=&quot;vertically-center-aligned md&quot;]/div[@class=&quot;w-100&quot;]/ion-card[@class=&quot;md&quot;]/ion-card-content[@class=&quot;md card-content-md&quot;]/p[3]</value>
      <webElementGuid>32aeab47-dc25-45d6-abc8-da25b248d1be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-modal[@id='ion-overlay-2']/div/ion-content/ion-grid/ion-row/div/ion-card/ion-card-content/p[3]</value>
      <webElementGuid>a1346c00-096e-4835-9515-26cc2348d353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send'])[1]/following::p[3]</value>
      <webElementGuid>c7ea6ad3-3b61-49c5-8d55-4fc5b3fa06e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/following::p[3]</value>
      <webElementGuid>f928ea66-d884-4a22-a94e-fcac128e4a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::p[1]</value>
      <webElementGuid>376bb4d9-6318-4d2a-a9bc-6457333be440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]</value>
      <webElementGuid>044bec38-6735-4507-bbb8-83b9ec4a668b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '0.99€ saved to your Piggy Bank Vault' or . = '0.99€ saved to your Piggy Bank Vault')]</value>
      <webElementGuid>8c8d8ee2-4781-44f7-bd57-e62c31b37a37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
