<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_1993-pen-f84-9e4</name>
   <tag></tag>
   <elementGuidId>ed8b0661-4dd2-4391-9900-b7bc1d66efd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.picker-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='1993']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>36abb043-55d4-4747-838b-e954b9c23dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f6c12ff6-8f59-4fcc-b669-fae4edf62ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>picker-item</value>
      <webElementGuid>ca67ae78-7eb5-4257-bc39-58e838855bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>1993</value>
      <webElementGuid>168af699-7aa8-4bee-bf15-6cf8f9fa5b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>70</value>
      <webElementGuid>409a776d-a605-4a01-ad50-3d1c2c359e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>wheel-item</value>
      <webElementGuid>357d01a4-0f4f-4f95-9cb7-f2bfa2672c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1993</value>
      <webElementGuid>9ad01d34-5f6a-4f49-99fe-655ed8a0e665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/button[@class=&quot;picker-item&quot;]</value>
      <webElementGuid>56f7faf2-914c-43cf-bf8d-befe9ae25869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TP41FilterTransactionsByDateRange/b/ion-picker-column-internal_year-column ion-color ion-color-primary md-er-open-f84</value>
      <webElementGuid>e732dea8-b796-4eb8-9e57-52954fb12d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3e382aa2-24e7-40d5-b977-3546c2121741</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1993']/parent::*</value>
      <webElementGuid>67ce0071-43c3-4b3e-a0a0-b2eb3547992f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '1993' or . = '1993')]</value>
      <webElementGuid>1c19cc66-4077-4406-8c8d-d2a435cd1cbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
