<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_1991-pen-f84-e2a</name>
   <tag></tag>
   <elementGuidId>c629ddbb-6eb3-4832-85eb-d232e8a995f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.picker-item.picker-item-active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='1991']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3edabf9d-90a6-4e2a-85be-081ab708b2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6958c459-fd7b-43ad-b7c0-52e89fcaa8cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>picker-item picker-item-active</value>
      <webElementGuid>0f28f473-4ee5-4d6e-99c1-4630f2741855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>1991</value>
      <webElementGuid>d841a049-e90f-4023-a827-7aa882e72107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>68</value>
      <webElementGuid>c4d2fa4e-44a3-410e-a748-cf1b83efc088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>wheel-item active</value>
      <webElementGuid>f09a2053-b0d7-4092-8240-6a911ea84517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1991</value>
      <webElementGuid>18c3a16b-2a19-406c-b005-d76c4dd98059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/button[@class=&quot;picker-item picker-item-active&quot;]</value>
      <webElementGuid>85410b77-9e11-415b-b725-0d924bf07b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TP41FilterTransactionsByDateRange/b/ion-picker-column-internal_year-column ion-color ion-color-primary md-er-open-f84</value>
      <webElementGuid>245da08d-8a55-4314-b7c9-b0525f22ca6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4d509174-a41c-4a09-886d-d3ef0ad498e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1991']/parent::*</value>
      <webElementGuid>c1ec4ada-e78c-4709-8447-3e934a80832e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '1991' or . = '1991')]</value>
      <webElementGuid>255f2422-8b8e-43a1-a1c2-c20a7b0f3b22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
