<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-button_User</name>
   <tag></tag>
   <elementGuidId>5e23722e-f64c-407e-9e18-73af28f61572</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'User' or . = 'User')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div > div > ion-button.md.button.button-solid.ion-activatable.ion-focusable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ion-router-outlet[@id='main-content']/div[2]/ion-content/div/div/div/div/div/ion-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-button</value>
      <webElementGuid>40d5705e-733f-4579-824a-d809dd4f2582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md button button-solid ion-activatable ion-focusable</value>
      <webElementGuid>c539d364-bc8f-45a0-bcec-a99b7588b49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/mydetails/900000001</value>
      <webElementGuid>aab586de-9042-4c49-aa87-287ff172c875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User</value>
      <webElementGuid>9571d920-e37a-4b1c-b4c1-02cf4d00ff8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ion-page can-go-back&quot;]/ion-content[@class=&quot;md content-ltr&quot;]/div[1]/div[1]/div[1]/div[1]/div[1]/ion-button[@class=&quot;md button button-solid ion-activatable ion-focusable&quot;]</value>
      <webElementGuid>6b32eee6-66e8-47c5-b276-f3bfeea8ff15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-router-outlet[@id='main-content']/div[2]/ion-content/div/div/div/div/div/ion-button</value>
      <webElementGuid>94f7bbc9-92c0-476e-8d4f-c4240e7868ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::ion-button[1]</value>
      <webElementGuid>27c11e12-a4a8-4105-80e2-eb899228f1c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balance'])[1]/preceding::ion-button[1]</value>
      <webElementGuid>7525af65-c83c-4bc6-8772-c72e5cf07c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Piggy Bank'])[1]/preceding::ion-button[1]</value>
      <webElementGuid>41370712-ee79-4f9a-9d23-03a11fcf509e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='User']/parent::*</value>
      <webElementGuid>c84a121e-2239-4ce2-b131-4d46994070eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ion-button</value>
      <webElementGuid>a919cf5f-49fe-4b1d-a1a1-28e72e7ebb99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-button[(text() = 'User' or . = 'User')]</value>
      <webElementGuid>5428833c-5dda-44b0-9722-db75106bb75c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
