<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>main_inner-scroll scroll-y-ailEdit-2e1</name>
   <tag></tag>
   <elementGuidId>44af0356-4cc7-4c69-9d57-22b1393d026b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>main.inner-scroll.scroll-y</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>6e619670-8d35-4430-bb13-a0d1a83a5718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inner-scroll scroll-y</value>
      <webElementGuid>ec23d5c1-49cd-4aba-b242-e596e9a67a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>scroll</value>
      <webElementGuid>4cc4d79b-ed48-42f1-8f4b-d1727aee9d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/main[@class=&quot;inner-scroll scroll-y&quot;]</value>
      <webElementGuid>c8564598-1a86-4217-a23a-7a0d3d859cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TP12ViewUserDetails/ion-content_Phone numberNameEmailEdit</value>
      <webElementGuid>c3781d87-9598-4f04-b817-790742041c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>891d2aea-4dcb-4f11-ace0-19561557a2df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>38a8708d-458f-416e-9419-7bdd327cb9ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
