<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mainPaginaProfileB</name>
   <tag></tag>
   <elementGuidId>f70ea2a4-dcca-4074-a547-7db678384cff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>main.inner-scroll.scroll-y</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>f238e873-df31-425a-a497-2e219d5e75e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inner-scroll scroll-y</value>
      <webElementGuid>40e13a29-c0ec-48b6-9a90-2dcbf7684de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>scroll</value>
      <webElementGuid>4825a4cf-3410-4e8b-bf34-22b3f00299e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/main[@class=&quot;inner-scroll scroll-y&quot;]</value>
      <webElementGuid>ec30d0f6-7358-4031-8cf6-fb1a801f34e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ce52fc39-544b-411d-8130-f529048c2f32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>020cc62d-8323-4467-98d7-180a603a0ecf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
