<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>slot-on_User-ebf</name>
   <tag></tag>
   <elementGuidId>df0dc686-bce9-48b6-a4ee-aeb1311b0f18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button-native > span.button-inner > slot:nth-of-type(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>slot</value>
      <webElementGuid>72196238-98ec-488c-a258-4e0218435fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/button[@class=&quot;button-native&quot;]/span[@class=&quot;button-inner&quot;]/slot[3]</value>
      <webElementGuid>0ceabf7f-7c1f-42f3-aea8-c3752ceae7d4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
