<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-row_Reference9000000172023-09-25 03540037.33</name>
   <tag></tag>
   <elementGuidId>c5c2c7e3-b809-4e1e-9788-53c96166d133</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ion-label.sc-ion-label-md-h.sc-ion-label-md-s.md > ion-grid.md > ion-row.md</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ion-router-outlet[@id='main-content']/div[3]/ion-content/div/div/ion-list/ion-item/ion-label/ion-grid/ion-row</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-row</value>
      <webElementGuid>15ca4644-f6bd-49ec-bd9b-43efa45ab887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md</value>
      <webElementGuid>c6e8e5f6-6bdc-4717-978c-2efffb3b610a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reference:9000000172023-09-25 03:54:00+37.33€</value>
      <webElementGuid>c3018a12-664d-443f-b94f-3dad0edebcdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ion-page can-go-back&quot;]/ion-content[@class=&quot;md content-ltr ion-padding&quot;]/div[1]/div[1]/ion-list[@class=&quot;md list-md&quot;]/ion-item[@class=&quot;item md item-lines-default item-fill-none in-list item-label&quot;]/ion-label[@class=&quot;sc-ion-label-md-h sc-ion-label-md-s md&quot;]/ion-grid[@class=&quot;md&quot;]/ion-row[@class=&quot;md&quot;]</value>
      <webElementGuid>9316444a-d89b-494e-b62b-18de1905e853</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-router-outlet[@id='main-content']/div[3]/ion-content/div/div/ion-list/ion-item/ion-label/ion-grid/ion-row</value>
      <webElementGuid>716c9783-5a65-4e1d-81e7-65a1b0d843da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::ion-row[1]</value>
      <webElementGuid>9f24f2f8-c767-427b-8644-de5b24af8805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT55551996822481613580421'])[1]/preceding::ion-row[6]</value>
      <webElementGuid>9b0c90b7-b760-4840-ae4f-7752ff8f7bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT73404309125064146196904'])[1]/preceding::ion-row[8]</value>
      <webElementGuid>5fb75750-e486-4629-963d-c2fb04418ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-label/ion-grid/ion-row</value>
      <webElementGuid>9a1dc218-0f79-483a-a9f2-bcb06fa988d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-row[(text() = 'Reference:9000000172023-09-25 03:54:00+37.33€' or . = 'Reference:9000000172023-09-25 03:54:00+37.33€')]</value>
      <webElementGuid>fb4a1709-3644-4a3d-83e8-bf269c12b3ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
