<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-select_AllDebitCredit (1)</name>
   <tag></tag>
   <elementGuidId>2d75cb12-33ee-4d3c-b90b-dd50dc37afca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ion-modal[@id='ion-overlay-2']/div/ion-content/ion-list/ion-item/ion-select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ion-select.md.in-item.has-value.has-placeholder.ion-focusable.select-ltr.select-justify-space-between.select-label-placement-start</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-select</value>
      <webElementGuid>913c639b-3c58-459c-a321-ed074af3fa15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md in-item has-value has-placeholder ion-focusable select-ltr select-justify-space-between select-label-placement-start</value>
      <webElementGuid>5b472aba-f539-444f-94b1-6d93ae6e187c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>modelvalue</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>25aa7fce-d189-4514-894b-0eb5dce36e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AllDebitCredit</value>
      <webElementGuid>49bb2f8d-cd8b-4077-a39b-3b20dbf50301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ion-overlay-2&quot;)/div[@class=&quot;ion-page&quot;]/ion-content[@class=&quot;ion-padding md content-ltr&quot;]/ion-list[@class=&quot;md list-md&quot;]/ion-item[@class=&quot;item md item-lines-default item-fill-none item-has-interactive-control in-list ion-activatable ion-focusable ion-activated&quot;]/ion-select[@class=&quot;md in-item has-value has-placeholder ion-focusable select-ltr select-justify-space-between select-label-placement-start&quot;]</value>
      <webElementGuid>62d82210-413b-45d3-8afc-7d2001485e2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-modal[@id='ion-overlay-2']/div/ion-content/ion-list/ion-item/ion-select</value>
      <webElementGuid>d2ae8f28-10fb-4f68-bc6d-471703ada31a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Date:'])[1]/following::ion-select[1]</value>
      <webElementGuid>bd2316c6-19be-45b3-8a73-a1837c3387fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Date:'])[1]/following::ion-select[1]</value>
      <webElementGuid>39139296-b8a2-4d16-8825-68129a081025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-select</value>
      <webElementGuid>dc8a5a00-2d5a-4915-aea9-ca27423efd18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-select[(text() = 'AllDebitCredit' or . = 'AllDebitCredit')]</value>
      <webElementGuid>ba167572-e1be-4e98-a29f-5b4aad6a2f31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
