<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-radio_Credit</name>
   <tag></tag>
   <elementGuidId>ae2eba8d-25b6-4f70-83d1-0e007db406ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ion-popover[@id='ion-overlay-3']/div/ion-select-popover/ion-list/ion-radio-group/ion-item[3]/ion-radio</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ion-item.select-interface-option.md.sc-ion-select-popover-md.item.item-lines-default.item-fill-none.item-has-interactive-control.ion-activatable.ion-focusable.ion-activated > ion-radio.sc-ion-select-popover-md.md.in-item.radio-justify-space-between.radio-alignment-center.radio-label-placement-start</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-radio</value>
      <webElementGuid>26497854-ba36-40d1-b859-e3fc2ea17f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-ion-select-popover-md md in-item radio-justify-space-between radio-alignment-center radio-label-placement-start</value>
      <webElementGuid>eec90e1b-e20c-4e3d-ba27-4ae3bec5aca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>53ac0001-d20f-4c03-bd86-8326b0fca5e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>afda6dac-aeeb-483f-80fb-3e51a542df50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2cdae9d5-290e-47ac-9e4e-c41e8d238b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Credit</value>
      <webElementGuid>05b93a4c-2da1-4a92-a893-a962045ae30e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ion-overlay-3&quot;)/div[@class=&quot;popover-viewport&quot;]/ion-select-popover[@class=&quot;sc-ion-select-popover-md-h sc-ion-select-popover-md-s md&quot;]/ion-list[@class=&quot;sc-ion-select-popover-md md list-md&quot;]/ion-radio-group[@class=&quot;sc-ion-select-popover-md md&quot;]/ion-item[@class=&quot;select-interface-option md sc-ion-select-popover-md item item-lines-default item-fill-none item-has-interactive-control ion-activatable ion-focusable ion-activated&quot;]/ion-radio[@class=&quot;sc-ion-select-popover-md md in-item radio-justify-space-between radio-alignment-center radio-label-placement-start&quot;]</value>
      <webElementGuid>a780f99f-0ade-422f-9553-405c1c56e7b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-popover[@id='ion-overlay-3']/div/ion-select-popover/ion-list/ion-radio-group/ion-item[3]/ion-radio</value>
      <webElementGuid>62ab5202-10ee-4251-a47a-ca78122ed503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Debit'])[2]/following::ion-radio[1]</value>
      <webElementGuid>569cc14c-0840-407b-b8fa-44d4b0ff76c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[2]/following::ion-radio[2]</value>
      <webElementGuid>e8797a41-74e3-42f2-9ebf-ce58b43aa02d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-item[3]/ion-radio</value>
      <webElementGuid>1c4e42ad-03d3-44c1-b251-42baedd1bf5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-radio[(text() = 'Credit' or . = 'Credit')]</value>
      <webElementGuid>4c788291-d08e-4de7-a05d-363bbf09093f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
