<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-select_AllDebitCredit (2)</name>
   <tag></tag>
   <elementGuidId>d0e7b55e-5b8b-4fb6-847b-044d9840a402</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ion-select.md.in-item.has-value.has-placeholder.ion-focusable.select-ltr.select-justify-space-between.select-label-placement-start</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ion-modal[@id='ion-overlay-2']/div/ion-content/ion-list/ion-item/ion-select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-select</value>
      <webElementGuid>b55b68d1-7a51-4e05-bf4c-77e8e508301a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md in-item has-value has-placeholder ion-focusable select-ltr select-justify-space-between select-label-placement-start</value>
      <webElementGuid>dd97b0ac-f291-447f-80bf-d3d5d83c326b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>modelvalue</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>b17863ee-5bbd-4b63-9bc6-d5d9f5f46876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AllDebitCredit</value>
      <webElementGuid>97e923e0-8bb3-4b49-8bc5-450b6e0225eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ion-overlay-2&quot;)/div[@class=&quot;ion-page&quot;]/ion-content[@class=&quot;ion-padding md content-ltr&quot;]/ion-list[@class=&quot;md list-md&quot;]/ion-item[@class=&quot;item md item-lines-default item-fill-none item-has-interactive-control in-list ion-activatable ion-focusable ion-activated&quot;]/ion-select[@class=&quot;md in-item has-value has-placeholder ion-focusable select-ltr select-justify-space-between select-label-placement-start&quot;]</value>
      <webElementGuid>9fb6db41-657f-4942-9b00-dd9de7862e2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-modal[@id='ion-overlay-2']/div/ion-content/ion-list/ion-item/ion-select</value>
      <webElementGuid>45ac7ec0-e5ea-4ced-b580-ecee33d1710a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Date:'])[1]/following::ion-select[1]</value>
      <webElementGuid>8ed57ffe-e7ea-494b-b3f8-cbb639f8e8c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Date:'])[1]/following::ion-select[1]</value>
      <webElementGuid>170fb42f-9c9e-43d3-9ff7-868f136c0778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-select</value>
      <webElementGuid>203d3b97-235d-4dab-a6a5-6c678e7a8a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-select[(text() = 'AllDebitCredit' or . = 'AllDebitCredit')]</value>
      <webElementGuid>c017fef8-6ce3-41c2-b8f6-ef6334b91a22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
