<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-radio_Debit</name>
   <tag></tag>
   <elementGuidId>b3103cf3-fa00-4e32-a89e-b345383a2e97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ion-popover[@id='ion-overlay-3']/div/ion-select-popover/ion-list/ion-radio-group/ion-item[2]/ion-radio</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ion-item.select-interface-option.md.sc-ion-select-popover-md.item.item-lines-default.item-fill-none.item-has-interactive-control.ion-activatable.ion-focusable.ion-activated > ion-radio.sc-ion-select-popover-md.md.in-item.radio-justify-space-between.radio-alignment-center.radio-label-placement-start</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-radio</value>
      <webElementGuid>576c09cb-6437-44d2-b029-498d3142e319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-ion-select-popover-md md in-item radio-justify-space-between radio-alignment-center radio-label-placement-start</value>
      <webElementGuid>b8aef6b0-5563-4e51-b6c3-46658f8d3a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>abb0327a-21f5-4029-8340-51915f251055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ee389ba1-c03a-4f96-8070-e0f5562a6e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1a8a703b-18ea-4daf-9572-cef93ee32784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Debit</value>
      <webElementGuid>86d3c320-1b62-46c4-8df3-1c2932551309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ion-overlay-3&quot;)/div[@class=&quot;popover-viewport&quot;]/ion-select-popover[@class=&quot;sc-ion-select-popover-md-h sc-ion-select-popover-md-s md&quot;]/ion-list[@class=&quot;sc-ion-select-popover-md md list-md&quot;]/ion-radio-group[@class=&quot;sc-ion-select-popover-md md&quot;]/ion-item[@class=&quot;select-interface-option md sc-ion-select-popover-md item item-lines-default item-fill-none item-has-interactive-control ion-activatable ion-focusable ion-activated&quot;]/ion-radio[@class=&quot;sc-ion-select-popover-md md in-item radio-justify-space-between radio-alignment-center radio-label-placement-start&quot;]</value>
      <webElementGuid>79eadc7f-e987-41af-9f8e-684f3caf3816</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-popover[@id='ion-overlay-3']/div/ion-select-popover/ion-list/ion-radio-group/ion-item[2]/ion-radio</value>
      <webElementGuid>7fe5a289-5eaa-457f-891a-4f56c4f79547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[2]/following::ion-radio[1]</value>
      <webElementGuid>ac35eae0-aeff-4523-a8e6-b1f3452df0cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit'])[1]/following::ion-radio[2]</value>
      <webElementGuid>ea830454-666d-4da2-a7d5-75c8b3c9b37c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit'])[2]/preceding::ion-radio[1]</value>
      <webElementGuid>bf8d9089-dfe7-4d4a-b05e-dfd67b639813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-item[2]/ion-radio</value>
      <webElementGuid>f2059fa2-f299-4f0f-955a-96f10231fd9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-radio[(text() = 'Debit' or . = 'Debit')]</value>
      <webElementGuid>8dba03aa-0993-4eca-acbb-d67e0083b830</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
