<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-icon_md flip-rtl-e-ready-fb7 (1)</name>
   <tag></tag>
   <elementGuidId>db5c372d-e586-49ec-82b7-e71f72cd65bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.datetime-calendar > div.calendar-header > div.calendar-action-buttons > div.calendar-month-year > ion-item.item.md.item-lines-none.item-fill-none.ion-activatable.ion-focusable.item-label.ion-activated > ion-label.sc-ion-label-md-h.sc-ion-label-md-s.md > ion-icon.md.flip-rtl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-icon</value>
      <webElementGuid>d8bd6344-3093-4eed-9e35-44c41ce87eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0aad452a-2fc1-4be8-aee0-26d3e00ca863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a7c79c97-8317-46f0-849d-5edc1bb2700e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md flip-rtl</value>
      <webElementGuid>654189c3-ba15-481c-b9b4-e1e527cbc030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;datetime-calendar&quot;]/div[@class=&quot;calendar-header&quot;]/div[@class=&quot;calendar-action-buttons&quot;]/div[@class=&quot;calendar-month-year&quot;]/ion-item[@class=&quot;item md item-lines-none item-fill-none ion-activatable ion-focusable item-label ion-activated&quot;]/ion-label[@class=&quot;sc-ion-label-md-h sc-ion-label-md-s md&quot;]/ion-icon[@class=&quot;md flip-rtl&quot;]</value>
      <webElementGuid>1f9d8c8d-1fa0-4114-8b33-c302eb927bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TP41FilterTransactionsByDateRange/Lixo/c/ion-datetime_Start Date_ion-color ion-color_49f10c (1)</value>
      <webElementGuid>cefcbaae-8f5c-4ebd-8334-671fe0c359de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ccb9b4f4-beeb-44d7-9aee-463a8d563016</webElementGuid>
   </webElementProperties>
</WebElementEntity>
