<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_1991-pen-f84-e2a (2)</name>
   <tag></tag>
   <elementGuidId>cc3c525a-bc8b-4f0d-80e3-69179645fa02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.picker-item.picker-item-active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='1991']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9fadcc91-078b-48e1-9b17-670a17dbeb89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>61ad5152-a220-4c49-be17-380c3afd4dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>picker-item picker-item-active</value>
      <webElementGuid>4a012d48-f82b-46c6-99ad-c713993de477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>1991</value>
      <webElementGuid>fd0e3d96-e004-4d7a-a93b-30481ec5d8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>68</value>
      <webElementGuid>85cb8d12-c2d4-414d-bdba-52a39f1a85ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>wheel-item active</value>
      <webElementGuid>ae47e2b7-7dfb-4052-a687-1659f2b1d798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1991</value>
      <webElementGuid>40023f7d-8d87-4e82-9dca-37d558a1a4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/button[@class=&quot;picker-item picker-item-active&quot;]</value>
      <webElementGuid>7df6b37c-d973-4724-b7f1-6237ac58e0ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TP41FilterTransactionsByDateRange/Page_Ionic App/ion-picker-column-internal_year-column ion-_b5c6af</value>
      <webElementGuid>67a423b2-76d7-43e4-8b9d-d5f8b1194a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>38ceacc6-ecd0-4299-8908-3597205a1839</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1991']/parent::*</value>
      <webElementGuid>e4c3adc7-b210-46b9-b95d-02d70b934deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '1991' or . = '1991')]</value>
      <webElementGuid>2438767a-d489-4e16-be2f-b94f203826b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
