<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_0000-e-ready-e97</name>
   <tag></tag>
   <elementGuidId>f368df75-d103-418c-b0d8-f2c5d7027632</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.datetime-time > button.time-body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='00:00']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e60b6af4-06ac-49fc-a129-5dc23ccc9732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>time-body</value>
      <webElementGuid>4a79adcb-ec09-4414-9e77-15473b6d0b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>time-button</value>
      <webElementGuid>5dfa2ba3-a4b3-4688-86a5-8510bdbf7038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c61d733b-c2a5-41d0-b398-e204fc1f78a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9a398974-8cd2-4525-9cbc-088fc9cbc853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>00:00</value>
      <webElementGuid>460bc718-74cb-4e5f-ae22-246f12bb9e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;datetime-time&quot;]/button[@class=&quot;time-body&quot;]</value>
      <webElementGuid>6fe78103-e481-4bb1-8092-302933b7602d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TP41FilterTransactionsByDateRange/Page_Ionic App/ion-datetime_Start Date_ion-color ion-color_49f10c (2)</value>
      <webElementGuid>bd5fa0d4-67f4-4ac3-b27a-dd56db38b73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a2138ca9-5768-467a-af2f-27b9df3ae40a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='00:00']/parent::*</value>
      <webElementGuid>19c14461-a988-433f-ae78-047938921695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '00:00' or . = '00:00')]</value>
      <webElementGuid>b24a3205-053b-44cf-8eb2-d1889caea8aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
