<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-picker-column-internal_year-column ion-_b5c6af</name>
   <tag></tag>
   <elementGuidId>1c8231a1-bf50-4f3d-9263-9e343920fa61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.datetime-year > div.wheel-order-month-first > ion-picker-internal > ion-picker-column-internal.year-column.ion-color.ion-color-primary.md</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-picker-column-internal</value>
      <webElementGuid>e96abc21-1c0f-4a12-9a68-4aeea2b14917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>year-column ion-color ion-color-primary md</value>
      <webElementGuid>74b71b1c-e4d8-4310-9959-f0ad90cf6822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>exportparts</name>
      <type>Main</type>
      <value>wheel-item, active</value>
      <webElementGuid>3dc6cfbc-97a2-4494-902a-f3461bee676c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f5168644-226b-4e9e-b1dd-c390cd3ec830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>3758e439-14db-4d83-bd5a-38e436c0edf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;datetime-year&quot;]/div[@class=&quot;wheel-order-month-first&quot;]/ion-picker-internal[1]/ion-picker-column-internal[@class=&quot;year-column ion-color ion-color-primary md&quot;]</value>
      <webElementGuid>dc62534f-b928-482c-8648-86d0f9b1e606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TP41FilterTransactionsByDateRange/Page_Ionic App/ion-datetime_Start Date_ion-color ion-color-primary md datetime-presentation-date-time datetime-size-fixed datetime-grid datetime-ready show-month-and-year month-year-picker-open</value>
      <webElementGuid>5d160979-2b9d-49b8-bd39-2590da470a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9d759f69-7160-4bcb-8fca-6377c0c6be2a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
