<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-icon_md flip-rtl-e-ready-fb7</name>
   <tag></tag>
   <elementGuidId>d6b367b8-0a7d-4dc8-998b-68e629b06aaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.datetime-calendar > div.calendar-header > div.calendar-action-buttons > div.calendar-month-year > ion-item.item.md.item-lines-none.item-fill-none.ion-activatable.ion-focusable.item-label.ion-activated > ion-label.sc-ion-label-md-h.sc-ion-label-md-s.md > ion-icon.md.flip-rtl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-icon</value>
      <webElementGuid>f37f3f6a-be36-41dd-bde1-d4d73b35e389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3fed1fa4-fc7e-43c1-8404-9f85b8e2c9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b59c5df2-f2e4-46d2-a301-f71cd9ab54d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md flip-rtl</value>
      <webElementGuid>21fd6cbf-9b0d-4cbe-9293-db16bf356a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;datetime-calendar&quot;]/div[@class=&quot;calendar-header&quot;]/div[@class=&quot;calendar-action-buttons&quot;]/div[@class=&quot;calendar-month-year&quot;]/ion-item[@class=&quot;item md item-lines-none item-fill-none ion-activatable ion-focusable item-label ion-activated&quot;]/ion-label[@class=&quot;sc-ion-label-md-h sc-ion-label-md-s md&quot;]/ion-icon[@class=&quot;md flip-rtl&quot;]</value>
      <webElementGuid>245ddb9c-085f-4c22-8085-c57c8b08854f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TP41FilterTransactionsByDateRange/Page_Ionic App/ion-datetime_Start Date_ion-color ion-color_49f10c</value>
      <webElementGuid>a6d66495-d6ad-473f-8f1b-ba3732994a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>461b3926-3843-4dca-a42c-23acc6117dd0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
