<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-backdrop_md-erlay-3-00a</name>
   <tag></tag>
   <elementGuidId>92ca42bf-9b7f-46aa-94ad-16f7d5234770</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ion-backdrop.md</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-backdrop</value>
      <webElementGuid>536a391d-5d5b-406c-b82a-59ef38e34caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>backdrop</value>
      <webElementGuid>73bcd15a-0240-4764-ac5c-c57e97fea8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>bccb7790-2ef2-4976-adf6-11a29d3858ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a5be1ccf-1ee7-406f-ab34-3615eb8b6114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md</value>
      <webElementGuid>4c261d0c-28d7-42d8-aae7-8fbfab6dd59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/ion-backdrop[@class=&quot;md&quot;]</value>
      <webElementGuid>5714e859-d089-44db-aa15-f6fe7876b2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TP41FilterTransactionsByDateRange/Page_Ionic App/ion-popover_Credit_ion-overlay-3</value>
      <webElementGuid>b6277468-5b18-4ad3-a7a3-f6ae6ccc7573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>600de5c8-5a3b-41dd-90bb-a452df7099fe</webElementGuid>
   </webElementProperties>
</WebElementEntity>
