<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-picker-column-internal_year-column</name>
   <tag></tag>
   <elementGuidId>5fd58f00-ddc4-41ff-acec-9e2c7c030ab6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.datetime-year > div.wheel-order-month-first > ion-picker-internal > ion-picker-column-internal.year-column.ion-color.ion-color-primary.md</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-picker-column-internal</value>
      <webElementGuid>f5655862-540f-4718-a3bd-65a8a5180a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>year-column ion-color ion-color-primary md</value>
      <webElementGuid>6517de05-1a89-46f2-9512-9fe51a9d0dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>exportparts</name>
      <type>Main</type>
      <value>wheel-item, active</value>
      <webElementGuid>da29508e-adf0-414c-a82e-9b749531081f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3890f465-88d0-4100-b8d1-102a458231de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>c3573fb6-1213-4981-85b7-a2a8bd5907d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;datetime-year&quot;]/div[@class=&quot;wheel-order-month-first&quot;]/ion-picker-internal[1]/ion-picker-column-internal[@class=&quot;year-column ion-color ion-color-primary md&quot;]</value>
      <webElementGuid>23a96555-6081-4fb8-a574-1876318cf5ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TP41FilterTransactionsByDateRange/Page_Ionic App/ion-datetime_Start Date_ion-color</value>
      <webElementGuid>ab389f94-217d-4216-9c8c-c3b7dae1f932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>38f3b5e2-5ca8-457d-b87a-58e79cc758f3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
