<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-item_Phone</name>
   <tag></tag>
   <elementGuidId>36f07592-8ffa-4787-ab09-9f0ff370f662</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ion-item.item-interactive.item-input.item.md.item-lines-default.item-fill-none.in-list.item-label.item-label-floating.item-has-focus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ion-router-outlet[@id='main-content']/div/ion-content/div/ion-list/ion-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-item</value>
      <webElementGuid>c1927dad-5df6-4d6e-81fa-ac7cf934a31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-interactive item-input item md item-lines-default item-fill-none in-list item-label item-label-floating item-has-focus</value>
      <webElementGuid>9faf50d0-752d-40ae-a2ae-899e63aa07ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listitem</value>
      <webElementGuid>b895088a-b1e1-4e1f-89c0-df9fd4e77a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Phone</value>
      <webElementGuid>929ba201-6636-468d-b063-8a519d428c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ion-page&quot;]/ion-content[@class=&quot;ion-padding md content-ltr&quot;]/div[@class=&quot;container&quot;]/ion-list[@class=&quot;list-container md list-md&quot;]/ion-item[@class=&quot;item-interactive item-input item md item-lines-default item-fill-none in-list item-label item-label-floating item-has-focus&quot;]</value>
      <webElementGuid>5dfd6305-8e5f-4c73-8450-15e65ffddf87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-router-outlet[@id='main-content']/div/ion-content/div/ion-list/ion-item</value>
      <webElementGuid>afb736fa-b433-4246-83c7-31c106eefb3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::ion-item[1]</value>
      <webElementGuid>25ec8472-3453-44db-9375-24712c6f2d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::ion-item[1]</value>
      <webElementGuid>ccc429f0-6e32-4acc-8c1d-e4a2e172e3c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::ion-item[1]</value>
      <webElementGuid>1b5c379f-9e5a-4b5a-b023-6dc852314add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-list/ion-item</value>
      <webElementGuid>2b955826-2fa7-49c5-97c1-4dc0479342ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-item[(text() = 'Phone' or . = 'Phone')]</value>
      <webElementGuid>c5cb49df-5e87-48c8-b0d2-c8247baa9f3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
