<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path-pen-191-c99</name>
   <tag></tag>
   <elementGuidId>0fa574e5-67a7-4103-8eb4-fb8dc9162c2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.icon-inner > svg.ionicon > path</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>8c5c2313-e4f7-4a19-a9e4-1642bf0d1f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M448 368L256 144 64 368h384z</value>
      <webElementGuid>3d52d9eb-f81f-4c70-8a4f-6a1284d62cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;icon-inner&quot;]/svg[@class=&quot;ionicon&quot;]/path[1]</value>
      <webElementGuid>9f2126d8-c83b-4aaf-81e5-ae29260c2f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TP41FilterTransactionsByDateRange/Page_Ionic App/ion-icon_md flip-rtl-er-open-191</value>
      <webElementGuid>67279a51-5a16-4131-833d-b66122ebaf96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fe04f2be-8cda-4679-8865-29888ee80fe1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
