<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>slot-n_Enter-fda</name>
   <tag></tag>
   <elementGuidId>ad06ff2b-17d4-4d6b-a90b-1cabacfa5538</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button-native > span.button-inner > slot:nth-of-type(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>slot</value>
      <webElementGuid>86164a88-15f9-42c2-a16c-2e2a5756cdf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/button[@class=&quot;button-native&quot;]/span[@class=&quot;button-inner&quot;]/slot[3]</value>
      <webElementGuid>825e9a6e-fbe2-43e6-8c6d-a35ff378ebf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TP43SortTransactionsByMostRecentOrHighestValue/ButtonsD/ion-button_Enter</value>
      <webElementGuid>cdbb4323-5c09-47e4-a9bf-50faffe55062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>30e2dc1d-d22c-4595-bb8b-d4f5e4b7e230</webElementGuid>
   </webElementProperties>
</WebElementEntity>
