<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b-total-balance</name>
   <tag></tag>
   <elementGuidId>bbc64e4b-1f13-44ce-8796-b2a4d23c7475</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>b:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ion-router-outlet[@id='main-content']/div[3]/ion-content/ion-row/ion-col/b[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>6a265ecd-5c18-4b3a-bf68-335748f6236f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>975,42 €</value>
      <webElementGuid>c0d344c7-2f50-4ed4-aa51-77b9daffa900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ion-page can-go-back&quot;]/ion-content[@class=&quot;md content-ltr&quot;]/ion-row[@class=&quot;md&quot;]/ion-col[@class=&quot;md&quot;]/b[2]</value>
      <webElementGuid>e2af6e9d-cda2-44ad-a243-04cf3aecc9f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-router-outlet[@id='main-content']/div[3]/ion-content/ion-row/ion-col/b[2]</value>
      <webElementGuid>ddb0fde0-661c-4b0a-a0b6-ba7d9cd7dd5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Balance:'])[1]/following::b[1]</value>
      <webElementGuid>52a637e7-51ae-494f-bbdd-f480d677c25b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Piggy Bank Vault'])[1]/following::b[2]</value>
      <webElementGuid>b95022f5-5301-4537-86e5-4dffb1ee087f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available Balance'])[1]/preceding::b[1]</value>
      <webElementGuid>d7f7b79c-682a-4fad-9757-6efe7757d01f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Piggy Bank Balance'])[1]/preceding::b[1]</value>
      <webElementGuid>fb58d6f1-5e85-43bf-9775-65fa3e91f25e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b[2]</value>
      <webElementGuid>a75eff1a-701f-4033-8a91-12433b20d9b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = '975,42 €' or . = '975,42 €')]</value>
      <webElementGuid>ed2ff867-2f02-42e0-b8e7-800b1d81b2de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
