<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Piggy Bank Balance_inputValue</name>
   <tag></tag>
   <elementGuidId>f7e526ea-7339-4f53-add0-4c89d2b7c658</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputValue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputValue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca45c982-d9fa-459c-8ee8-d37b51582331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputValue</value>
      <webElementGuid>27ec1e7c-9b3a-4b23-b9b5-c916d5b778d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6371a847-66cc-4041-bebb-b04d9132d929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0,00€</value>
      <webElementGuid>5d53e925-ba8f-4f06-a51a-dbcdbea3c24b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>d217c51e-c826-4b7b-a4ca-1cdb5b5f1e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputValue&quot;)</value>
      <webElementGuid>aa183d45-e4e9-482d-a526-b95150fd1f6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputValue']</value>
      <webElementGuid>acb98eab-8c3c-41d6-8e2c-a75e8ddc678d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-router-outlet[@id='main-content']/div[3]/ion-content/ion-row/ion-col[3]/input</value>
      <webElementGuid>a63ccd82-8e58-4a0e-8d70-1cc0f7438529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-col[3]/input</value>
      <webElementGuid>a71b5bdc-6a78-471e-ab7c-98bcd8902b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputValue' and @type = 'text' and @placeholder = '0,00€']</value>
      <webElementGuid>38a1212d-2af2-4c54-a0ba-e59bcdf64efb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
