<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-button-switch-action</name>
   <tag></tag>
   <elementGuidId>586b2f7c-31bc-4757-9d8a-7a4ebc5c0dae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.flow-transfer-container > ion-button.md.button.button-clear.ion-activatable.ion-focusable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ion-router-outlet[@id='main-content']/div[3]/ion-content/ion-row/ion-col[2]/div[2]/ion-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-button</value>
      <webElementGuid>85a7d973-7d4d-45ca-9a95-5cdf077a68ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md button button-clear ion-activatable ion-focusable</value>
      <webElementGuid>88eaa8ba-d0f9-418a-82b9-ec2b61f12f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>clear</value>
      <webElementGuid>3bfb6d1b-b272-42da-bde9-f9fb9b678516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ion-page can-go-back&quot;]/ion-content[@class=&quot;md content-ltr&quot;]/ion-row[@class=&quot;md&quot;]/ion-col[@class=&quot;md&quot;]/div[@class=&quot;flow-transfer-container&quot;]/ion-button[@class=&quot;md button button-clear ion-activatable ion-focusable&quot;]</value>
      <webElementGuid>61064285-5dc8-4286-a488-104c8721292b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-router-outlet[@id='main-content']/div[3]/ion-content/ion-row/ion-col[2]/div[2]/ion-button</value>
      <webElementGuid>692c751c-0555-4370-bf71-0f864bf0b2fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available Balance'])[1]/following::ion-button[1]</value>
      <webElementGuid>3515dfa5-8c67-4a83-8393-b3f5137f2cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Balance:'])[1]/following::ion-button[1]</value>
      <webElementGuid>ef929ad4-7b70-4719-b8f9-b2622edeb969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Piggy Bank Balance'])[1]/preceding::ion-button[1]</value>
      <webElementGuid>3f18b0ef-5fe3-4965-9af6-3f6a5cd3972b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/preceding::ion-button[1]</value>
      <webElementGuid>9823e4fd-ba47-40e8-b872-5c9a79728cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ion-button</value>
      <webElementGuid>028f9911-29df-437e-bf40-d0274268aae1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
