<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>slot-Success-4db</name>
   <tag></tag>
   <elementGuidId>253907de-dc54-4d39-9132-2bd793dd26a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>slot</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>slot</value>
      <webElementGuid>08583305-9067-44ce-a9d3-218e0bd3fb2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/slot[1]</value>
      <webElementGuid>7f4fa5ea-fa68-4d11-b093-8ef0015f568a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TP28SubtractMyPiggyBankBalance/ion-card-title_Success</value>
      <webElementGuid>009a1dcc-a315-4236-93c3-4b5bef66ccbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1786ac8c-4189-49b5-885c-0e10c729cf90</webElementGuid>
   </webElementProperties>
</WebElementEntity>
