<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Piggy Bank Balance_ion-input-4 (1)</name>
   <tag></tag>
   <elementGuidId>1b674b53-c199-44a1-b22c-90a84f571e65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ion-input-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ion-input-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c6ce6cf-dff6-4a52-8fdf-458da3498a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>native-input sc-ion-input-md</value>
      <webElementGuid>f5aafa58-c9c6-4b7b-bcc0-3778e6a59451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ion-input-4</value>
      <webElementGuid>43dcc9dc-4346-441e-ad2e-d4fdb5dd042e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>72b8606c-6509-49ac-b6bd-78835ad5e51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>80ec8312-0941-4df5-96d1-61dfd4ce4881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>efde8c78-ec38-41d3-b73c-aa857748eb90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ion-input-4</value>
      <webElementGuid>befcd9ea-4c19-472e-bcce-e6352a21d352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0,00</value>
      <webElementGuid>c1b2a94d-07a9-4488-99bd-0037005ceeda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a8322f1c-233d-4a76-a44c-5abfc979deb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>f0b879fa-ec6f-4205-9f7a-5640bbe592a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ion-input-4&quot;)</value>
      <webElementGuid>5dbce629-da67-481c-bc04-35b85959fd43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ion-input-4']</value>
      <webElementGuid>9e8dd9c3-469b-4bfc-95f3-05a1dd97fddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-router-outlet[@id='main-content']/div[3]/ion-content/ion-row/ion-col[3]/ion-input/label/div[2]/input</value>
      <webElementGuid>6d0ff43c-5c79-4016-b4c7-6f25c2768c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>1c8d2e2c-a2d9-4528-aef9-4123bd776f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ion-input-4' and @name = 'ion-input-4' and @placeholder = '0,00' and @type = 'number']</value>
      <webElementGuid>cfc12f24-1bde-412f-a173-cac23948065e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
