<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-toggle_Settings_md in-item toggle-check_4e4602</name>
   <tag></tag>
   <elementGuidId>04b6921c-d3f5-4a4b-bb50-f2632d7bf61c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ion-router-outlet[@id='main-content']/div[3]/ion-content/ion-item/ion-toggle</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ion-toggle.md.in-item.toggle-checked.legacy-toggle.interactive.toggle-ltr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-toggle</value>
      <webElementGuid>ca7fd8bf-1434-4121-b550-b93ab987f92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md in-item toggle-checked legacy-toggle interactive toggle-ltr</value>
      <webElementGuid>390b748f-d1d9-44f0-82fb-fb5bcf262a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>ion-tg-0-lbl</value>
      <webElementGuid>945be149-1e1a-4534-9fc3-0b3fdbd39bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>35afa299-fd7f-48c0-9fa6-b18a96436ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>6698c00b-4de6-4cf9-907f-cc6f998e8d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ion-page can-go-back&quot;]/ion-content[@class=&quot;md content-ltr ion-padding&quot;]/ion-item[@class=&quot;item md item-lines-default item-fill-none item-has-interactive-control item-label&quot;]/ion-toggle[@class=&quot;md in-item toggle-checked legacy-toggle interactive toggle-ltr&quot;]</value>
      <webElementGuid>be9309f9-b9d5-41d2-b691-8cb4fc7568bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-router-outlet[@id='main-content']/div[3]/ion-content/ion-item/ion-toggle</value>
      <webElementGuid>4af2a216-b739-443c-9dc5-8bee7b351133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/following::ion-toggle[1]</value>
      <webElementGuid>c24263bd-3bdb-4723-9209-0983dd458d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show More'])[1]/following::ion-toggle[1]</value>
      <webElementGuid>33fd93eb-4e30-4fa2-a8ab-870eddac4f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-toggle</value>
      <webElementGuid>03b06877-64ba-4c53-b7aa-526e17b6b7d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
