<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-label_Send</name>
   <tag></tag>
   <elementGuidId>2101b35e-c541-49cc-a188-983b65dbbd11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ion-router-outlet[@id='main-content']/div[4]/ion-content/div/ion-row/ion-card/ion-card-content/ion-button/ion-label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ion-label.sc-ion-label-md-h.sc-ion-label-md-s.md.ion-label-w-spinner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-label</value>
      <webElementGuid>02296958-fe06-4340-af18-ea8c5664020d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-ion-label-md-h sc-ion-label-md-s md ion-label-w-spinner</value>
      <webElementGuid>5c4c41ab-4bf1-4d07-a702-24284021b4cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send </value>
      <webElementGuid>1b992f46-e6b0-4bce-a932-4e8a0d60b618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ion-page can-go-back&quot;]/ion-content[@class=&quot;md content-ltr ion-padding&quot;]/div[@class=&quot;d-flex flex-column justify-content-space-between h-100&quot;]/ion-row[@class=&quot;md ion-justify-content-center w-100&quot;]/ion-card[@class=&quot;md w-100&quot;]/ion-card-content[@class=&quot;md card-content-md&quot;]/ion-button[@class=&quot;md button button-solid ion-activatable ion-focusable ion-activated&quot;]/ion-label[@class=&quot;sc-ion-label-md-h sc-ion-label-md-s md ion-label-w-spinner&quot;]</value>
      <webElementGuid>d914dde4-ae2b-4f27-8f85-c3551d26db74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-router-outlet[@id='main-content']/div[4]/ion-content/div/ion-row/ion-card/ion-card-content/ion-button/ion-label</value>
      <webElementGuid>09194525-e7cb-4944-a6aa-0871b5676bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/following::ion-label[1]</value>
      <webElementGuid>f3b7318f-9b2b-4c0d-bea8-42064de8fb2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send to:'])[1]/following::ion-label[1]</value>
      <webElementGuid>0b393394-94df-4c8e-945d-a25a16b8e1a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-card-content/ion-button/ion-label</value>
      <webElementGuid>d2065945-24b9-4774-89b5-904564654946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-label[(text() = 'Send ' or . = 'Send ')]</value>
      <webElementGuid>07e7329a-9aeb-4988-82ed-99ef86cac400</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
