<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-button_Continue</name>
   <tag></tag>
   <elementGuidId>45863182-f0f3-4deb-b69d-04fc899d4311</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ion-modal[@id='ion-overlay-2']/div/ion-content/ion-grid/ion-row/div[2]/ion-button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ion-button.ion-color.ion-color-success.md.button.button-full.button-solid.ion-activatable.ion-focusable.ion-activated</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-button</value>
      <webElementGuid>1b0acce2-a7e7-4730-84d6-f942593a0289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ion-color ion-color-success md button button-full button-solid ion-activatable ion-focusable ion-activated</value>
      <webElementGuid>2a4d783e-47f3-478e-ace8-544bf2dc6052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>success</value>
      <webElementGuid>fd26d933-7481-459f-af94-ce11a34a71fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>expand</name>
      <type>Main</type>
      <value>full</value>
      <webElementGuid>d508e18e-f0d0-4cb6-bf4e-2799e595e9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>5792dfcb-456c-4e89-9edd-b0d6150dd9db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ion-overlay-2&quot;)/div[@class=&quot;ion-delegate-host ion-page&quot;]/ion-content[@class=&quot;ion-text-center md content-ltr&quot;]/ion-grid[@class=&quot;md vertically-center-aligned&quot;]/ion-row[@class=&quot;vertically-center-aligned md&quot;]/div[@class=&quot;w-100&quot;]/ion-button[@class=&quot;ion-color ion-color-success md button button-full button-solid ion-activatable ion-focusable ion-activated&quot;]</value>
      <webElementGuid>d937d369-94d3-48ee-ac4d-15a001ca0cad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-modal[@id='ion-overlay-2']/div/ion-content/ion-grid/ion-row/div[2]/ion-button</value>
      <webElementGuid>f5bddc5b-eefa-4406-898b-e8a183be5bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send'])[1]/following::ion-button[1]</value>
      <webElementGuid>f6686841-80f3-4d00-b533-f3e92d8c3824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/following::ion-button[2]</value>
      <webElementGuid>3a25d958-3b11-4eab-9b2c-449c82927282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ion-button</value>
      <webElementGuid>b3633308-777a-44f4-b7dc-9e2eb493b253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-button[(text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>ce5c9367-2e27-4550-9c23-2148321b0fae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
