<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-toggle2</name>
   <tag></tag>
   <elementGuidId>b7603d11-7b3d-4352-9eb9-5d80498160ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ion-router-outlet[@id='main-content']/div[3]/ion-content/ion-item/ion-toggle</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ion-toggle.md.in-item.toggle-checked.legacy-toggle.interactive.toggle-ltr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-toggle</value>
      <webElementGuid>19ba90f4-b9e0-4645-880d-a42417815bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md in-item toggle-checked legacy-toggle interactive toggle-ltr</value>
      <webElementGuid>d2684b48-a490-48f0-a427-2b0b10253b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>ion-tg-0-lbl</value>
      <webElementGuid>c830be44-0200-45e7-aad2-6133d973b0ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4220dbe2-f052-4d9c-9c72-889879534ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>bb2b7c80-843d-43df-b518-76ba52e27b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ion-page can-go-back&quot;]/ion-content[@class=&quot;md content-ltr ion-padding&quot;]/ion-item[@class=&quot;item md item-lines-default item-fill-none item-has-interactive-control item-label&quot;]/ion-toggle[@class=&quot;md in-item toggle-checked legacy-toggle interactive toggle-ltr&quot;]</value>
      <webElementGuid>0724ee52-cb46-4445-ab65-244b1a6ad658</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-router-outlet[@id='main-content']/div[3]/ion-content/ion-item/ion-toggle</value>
      <webElementGuid>88a30716-49f6-4ba4-a399-9654db2d5b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/following::ion-toggle[1]</value>
      <webElementGuid>48f20ef8-cb9d-4f8b-8c80-3e9e5e7a7a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show More'])[1]/following::ion-toggle[1]</value>
      <webElementGuid>65344813-1428-4c87-b713-12e15a2a1678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::ion-toggle[2]</value>
      <webElementGuid>dc97bd89-61e8-4b9e-bae4-47d639229556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::ion-toggle[2]</value>
      <webElementGuid>ab28d25d-0c7a-40c6-91dc-7e0b4e94fc1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-toggle</value>
      <webElementGuid>7b342674-1f24-4485-822b-2977bc6c4133</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
