<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-button_SortAmount</name>
   <tag></tag>
   <elementGuidId>45a2f6b1-c54a-4792-aab5-57b4c71ce9cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ion-button.md.button.button-solid.ion-activatable.ion-focusable.custom-button-sorts.euro-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ion-router-outlet[@id='main-content']/div[3]/ion-content/div/div/div/div[2]/ion-button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-button</value>
      <webElementGuid>c27a3bb1-d332-485a-9729-a4d6fc8bbcca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md button button-solid ion-activatable ion-focusable custom-button-sorts euro-button</value>
      <webElementGuid>3074332e-3d5c-40c0-9738-79e209f79eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ion-page can-go-back&quot;]/ion-content[@class=&quot;md content-ltr ion-padding&quot;]/div[1]/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;sorts&quot;]/ion-button[@class=&quot;md button button-solid ion-activatable ion-focusable custom-button-sorts euro-button&quot;]</value>
      <webElementGuid>719b5b42-066c-42bf-92d2-9eed68f35de4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-router-outlet[@id='main-content']/div[3]/ion-content/div/div/div/div[2]/ion-button[2]</value>
      <webElementGuid>577de4b8-7b19-42eb-bc04-82fc69b465cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters'])[1]/following::ion-button[2]</value>
      <webElementGuid>3b0bec30-4fac-4922-a55c-12963cebf377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transactions'])[1]/following::ion-button[3]</value>
      <webElementGuid>db8485f2-6ae3-4f89-87f5-45d52c0120ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='lourenco64@yahoo.com'])[1]/preceding::ion-button[2]</value>
      <webElementGuid>1476aea7-a690-4d9a-aae9-acdd1d8287ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT47093729601003645111636'])[1]/preceding::ion-button[2]</value>
      <webElementGuid>9fb4dc2d-1713-4e43-ba05-e6be5c33d1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-button[2]</value>
      <webElementGuid>ef3f45c5-9aa2-41b2-8cb3-d1052a0edbbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
