<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_31-e-ready-c68</name>
   <tag></tag>
   <elementGuidId>664ab64c-9200-4ea3-9fe5-2036704c8897</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.datetime-calendar > div.calendar-body.ion-focusable > div.calendar-month > div.calendar-month-grid > div.calendar-day-wrapper > button.calendar-day</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='31']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cadf6f84-8244-4f0a-af68-454407031dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7a5dbb56-f386-46ac-a17b-a0d7cf7244f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-day</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>f50b0b27-2ae4-440d-badc-9479eac39efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-month</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>918b83b6-b371-48bb-8f9e-cf7b5bdd2714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-year</name>
      <type>Main</type>
      <value>2024</value>
      <webElementGuid>efc00964-270b-4b76-937f-1fb3e17020c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>f10793d3-f356-49c8-9295-912d1d519270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-day-of-week</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>e56c5ca9-ea4e-4267-ab5c-a96519bb07d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calendar-day</value>
      <webElementGuid>80761a75-a181-4233-a61d-e953c4f3064e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>calendar-day</value>
      <webElementGuid>4560c9b6-a313-4bdf-9442-f752aa60759c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>quarta-feira, 31 de janeiro</value>
      <webElementGuid>067a03de-9881-4bcf-8688-e81bd6b2dcc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>8108b406-308b-4e23-8187-1d8ff649ef16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;datetime-calendar&quot;]/div[@class=&quot;calendar-body ion-focusable&quot;]/div[@class=&quot;calendar-month&quot;]/div[@class=&quot;calendar-month-grid&quot;]/div[@class=&quot;calendar-day-wrapper&quot;]/button[@class=&quot;calendar-day&quot;]</value>
      <webElementGuid>64037556-c48a-4313-a22d-9dd8c0a68fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TP41FilterTransactionsByDateRange/a/ion-datetime_End Date_ion-color ion-color-primary md datetime-presentation-date-time datetime-size-fixed datetime-grid datetime-ready</value>
      <webElementGuid>f7af74bc-cdaf-42a0-8639-f9872dbf9bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3ce7707b-b3d1-42a8-8fee-92abb213a191</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='31']/parent::*</value>
      <webElementGuid>b735a565-6d9d-47a6-838e-c2120f66d0aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '31' or . = '31')]</value>
      <webElementGuid>2d723fa8-ff36-4d66-84bf-e76dc9890124</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
