<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_2023-pen-839-c0e</name>
   <tag></tag>
   <elementGuidId>7ac69cdf-bbdd-4e74-b328-0ee9d22112a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.picker-item.picker-item-active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='2023']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bd612bca-2a7b-4aca-bb66-54e1660172bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>19f1b094-c97a-46f5-9633-8a2df1c7162c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>picker-item picker-item-active</value>
      <webElementGuid>0fcd3df1-5810-4050-bcfd-98a6d426f685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>2023</value>
      <webElementGuid>c19fbe92-8ff3-4016-8149-0e8bd2fd61f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>54dc5667-5bc1-44d5-a5a4-e565864090ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>wheel-item active</value>
      <webElementGuid>ec359b47-ff5b-4fc4-a5dd-c0c78227c2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2023</value>
      <webElementGuid>a7ad48be-0852-4f4e-953b-5c5fdcac2c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/button[@class=&quot;picker-item picker-item-active&quot;]</value>
      <webElementGuid>99b4c9a8-aff6-43ec-b425-c5150fac4378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TP41FilterTransactionsByDateRange/Lixo/a/ion-picker-column-internal_year-column ion-color ion-color-primary md-er-open-839</value>
      <webElementGuid>2e9c3d12-2038-4c7a-97af-9e405c7623b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ffe7cefe-e81d-4ad5-898d-5365dfae7710</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2023']/parent::*</value>
      <webElementGuid>1a5355ec-303a-4d0d-9950-bf25fee7c85e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '2023' or . = '2023')]</value>
      <webElementGuid>ae676c88-c3b3-4d50-af3f-5410815182a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
