<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_1955-e-ready-3aa</name>
   <tag></tag>
   <elementGuidId>8cd8d85c-4d2a-46d9-abea-acada7b94c23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.datetime-time > button.time-body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='19:55']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>26008da7-b9d3-4d95-8870-7c2fe9cb9c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>time-body</value>
      <webElementGuid>bc8b149d-ce18-47e6-9493-edd7a34b9ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>time-button</value>
      <webElementGuid>ded24bfb-5918-4c55-82bc-11bf000179ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c5cd9726-e07b-4604-8663-5d6d1719ed0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5bfcd77b-f8e1-48fb-b499-50414366920a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>19:55</value>
      <webElementGuid>3a35a95b-4eb9-4c68-a081-6463c25d2eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;datetime-time&quot;]/button[@class=&quot;time-body&quot;]</value>
      <webElementGuid>47e30160-a3c0-43fd-9d65-a5a0f571a379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TP41FilterTransactionsByDateRange/a/ion-datetime_End Date_ion-color ion-color-primary md datetime-presentation-date-time datetime-size-fixed datetime-grid datetime-ready</value>
      <webElementGuid>9a9daa19-4035-4894-a4a8-e92b4bf7a83a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c33bed67-1beb-4973-a5f1-e490db28af3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='19:55']/parent::*</value>
      <webElementGuid>50c7a347-01d0-4486-905a-0acc70dd7440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '19:55' or . = '19:55')]</value>
      <webElementGuid>fae8c682-f9f5-4e44-a125-08cc8bc4234f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
