<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-popover_Credit_ion-overlay-4</name>
   <tag></tag>
   <elementGuidId>b3554fce-8eb1-4af6-8cc6-b78ef7653c31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ion-overlay-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ion-popover[@id='ion-overlay-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-popover</value>
      <webElementGuid>a79ad4f3-fa27-4107-bf9a-baac5249957d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ion-overlay-4</value>
      <webElementGuid>b8cd58ba-0351-412a-8964-b0de3be703f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7c5e934c-e975-47a7-a32a-3ef29de54a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>559a79cc-f4fb-4a31-b7bc-ca2d01872b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md popover-translucent popover-desktop popover-side-bottom</value>
      <webElementGuid>b5217230-866e-4833-a255-05fb89e755ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ion-overlay-4&quot;)</value>
      <webElementGuid>3e3c708a-9220-44b7-8de6-047f80fd1b83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ion-popover[@id='ion-overlay-4']</value>
      <webElementGuid>dd3ce4e5-1a50-48b1-acb8-d30cad82974c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/ion-app/ion-popover</value>
      <webElementGuid>428d8548-adb9-4392-9f44-760212186942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit'])[1]/following::ion-popover[1]</value>
      <webElementGuid>9d82f387-aa54-49ad-806a-df7038c1f016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Debit'])[1]/following::ion-popover[1]</value>
      <webElementGuid>7cee2984-92d4-4752-8ea4-fcee6a6ab251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('/ion-backdrop[@class=', '&quot;', 'md', '&quot;', ']')])[1]/preceding::ion-popover[1]</value>
      <webElementGuid>dc208b11-364f-4d74-b450-fb629e48936a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-popover</value>
      <webElementGuid>69128c68-5755-414e-ba81-8903d7e7024c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-popover[@id = 'ion-overlay-4']</value>
      <webElementGuid>f3e8dfd6-58b7-45fc-aee0-0e64fdd3e7f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
