<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-backdrop_md-erlay-3-00a</name>
   <tag></tag>
   <elementGuidId>baf9ba95-58ba-4de9-a8bb-b6d1bfab46d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ion-backdrop.md</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-backdrop</value>
      <webElementGuid>feae7dd5-64f4-486d-9ad0-2faf9614fd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>backdrop</value>
      <webElementGuid>57eef323-82bd-4e66-aacd-a3a9db3d4e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c57ae8be-63fa-479b-aa1a-db4fea6a4e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7219e752-acb1-48a1-82f3-2e87acb05e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md</value>
      <webElementGuid>8169fdf2-d717-431d-8511-2279e86d337f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/ion-backdrop[@class=&quot;md&quot;]</value>
      <webElementGuid>14246a61-73a8-4cfb-aa34-2f68b9c432b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TP41FilterTransactionsByDateRange/Lixo/a/ion-popover_Credit_ion-overlay-3</value>
      <webElementGuid>9ef75d45-6371-4b99-b390-6035ba849303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9679333b-e91b-4667-9aa8-ccf574fdb51e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
