<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-picker-column-internal_year-column ion-color ion-color-primary md-er-open-839</name>
   <tag></tag>
   <elementGuidId>66624496-09e2-4b63-ab23-d66cb1426391</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.datetime-year > div.wheel-order-month-first > ion-picker-internal > ion-picker-column-internal.year-column.ion-color.ion-color-primary.md</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-picker-column-internal</value>
      <webElementGuid>c42b55a1-1757-4cb5-b75c-a26ac8d005d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>year-column ion-color ion-color-primary md</value>
      <webElementGuid>6b95593e-8245-44d8-b7dc-f64ce2822f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>exportparts</name>
      <type>Main</type>
      <value>wheel-item, active</value>
      <webElementGuid>0f9fa907-d1d9-4133-9c77-39a15ccfe47f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>730dc2de-24e2-40cb-b747-6e2e02aee3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>74cbb053-987d-4dbc-add5-8f0148620148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;datetime-year&quot;]/div[@class=&quot;wheel-order-month-first&quot;]/ion-picker-internal[1]/ion-picker-column-internal[@class=&quot;year-column ion-color ion-color-primary md&quot;]</value>
      <webElementGuid>7070a795-4932-4922-8cb7-c200cb999a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TP41FilterTransactionsByDateRange/Lixo/a/ion-datetime_End Date_ion-color ion-color-p_7266dd</value>
      <webElementGuid>03f99fa1-505a-4ecb-9a7b-d141a50c6a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>040eb3f7-b137-4b99-9ca3-cf05610e0cd7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
