<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-picker-column-internal_Credit_ion-color_cdb06e_1</name>
   <tag></tag>
   <elementGuidId>149e039d-b713-4ffe-a77a-80fda55987d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ion-popover[@id='ion-overlay-4']/div/ion-picker-internal/ion-picker-column-internal[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-picker-column-internal</value>
      <webElementGuid>9902432d-fc46-4abf-8c6d-8b6b1bf3aef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>exportparts</name>
      <type>Main</type>
      <value>wheel-item, active</value>
      <webElementGuid>10783624-0358-4715-9901-08652712ded3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d897f829-f1ab-4659-9f33-19d1b0df3e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ion-color ion-color-primary md picker-column-numeric-input</value>
      <webElementGuid>557caa68-b65e-4d96-a1e0-10bb8d4a4ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>e4dc4bed-5fe0-4e93-8ac3-16e0d269c2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ion-overlay-4&quot;)/div[@class=&quot;ion-delegate-host popover-viewport&quot;]/ion-picker-internal[1]/ion-picker-column-internal[@class=&quot;ion-color ion-color-primary md picker-column-numeric-input&quot;]</value>
      <webElementGuid>0823a754-5b6e-40aa-81e4-678632acbcf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-popover[@id='ion-overlay-4']/div/ion-picker-internal/ion-picker-column-internal[2]</value>
      <webElementGuid>eeff7b64-ea51-432b-bf0c-bf8ebb4b8a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-picker-column-internal[2]</value>
      <webElementGuid>56724910-169d-42ed-8c5c-b4ad0f705643</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
