<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_7-e-ready-880</name>
   <tag></tag>
   <elementGuidId>164d1cc8-c6f4-4343-b757-f07c9ad6e2ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.datetime-calendar > div.calendar-body.ion-focusable > div.calendar-month > div.calendar-month-grid > div.calendar-day-wrapper > button.calendar-day</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='7']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>412916e7-06f9-485d-8a2f-54be1f688618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3788ff16-7ba9-46e0-9096-ee28cf91d3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-day</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>d97111f1-fe84-411e-b9c7-71a107873414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-month</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a8f9e5c6-f78c-4c17-ae99-123b59db9f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-year</name>
      <type>Main</type>
      <value>2023</value>
      <webElementGuid>66bc7f5a-81d7-4859-8237-a9e56d56ebd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>648173fd-3706-4913-bd27-eb76f534fc37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-day-of-week</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>2ba2bc89-7c2b-4dea-9194-2622778b10f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calendar-day</value>
      <webElementGuid>4e4482ae-e4b5-4603-9f80-1a8827b2ede4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>calendar-day</value>
      <webElementGuid>61dc61a4-1026-4e30-a4eb-208668e1d799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>terça-feira, 7 de fevereiro</value>
      <webElementGuid>38213e7b-8502-4627-b70d-f9441ba14e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>97753d66-0bbc-4aee-9671-4f1ca66f87cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;datetime-calendar&quot;]/div[@class=&quot;calendar-body ion-focusable&quot;]/div[@class=&quot;calendar-month&quot;]/div[@class=&quot;calendar-month-grid&quot;]/div[@class=&quot;calendar-day-wrapper&quot;]/button[@class=&quot;calendar-day&quot;]</value>
      <webElementGuid>949aceee-89d0-471d-9e45-65fa24e9f251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TP41FilterTransactionsByDateRange/dia7/ion-datetime_Start Date_ion-color ion-color-primary md datetime-presentation-date-time datetime-size-fixed datetime-grid datetime-ready</value>
      <webElementGuid>cb1c2f81-6609-4a3c-bc76-8a8190cda7a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6b990e0a-fcb3-4c9b-a0b9-a14e2123b104</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='7']/parent::*</value>
      <webElementGuid>6a97e27b-9fa5-4623-b8e5-5081628051e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '7' or . = '7')]</value>
      <webElementGuid>6a1ca75d-bade-4ed8-83d2-7371173f1a6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
