<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-non_vcard_contact</name>
   <tag></tag>
   <elementGuidId>47db5dc8-c43e-48c8-8b84-62a49d672b6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ion-router-outlet[@id='main-content']/div[3]/ion-content/div/div[2]/ion-list/ion-item-sliding/ion-item/ion-label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ion-item-sliding.md > ion-item.item-has-start-slot.item.md.item-lines-default.item-fill-none.in-list.ion-activatable.ion-focusable.item-label > ion-label.sc-ion-label-md-h.sc-ion-label-md-s.md</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-label</value>
      <webElementGuid>5f217d72-b420-4c1f-975c-47a6c0de6026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-ion-label-md-h sc-ion-label-md-s md</value>
      <webElementGuid>f3ba41e5-7ae2-4056-9d90-7a7c8ac026b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Afonso Cancela918821097</value>
      <webElementGuid>32afe747-9674-4eba-a44d-879abdc3cb2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ion-page can-go-back&quot;]/ion-content[@class=&quot;md content-ltr&quot;]/div[1]/div[2]/ion-list[@class=&quot;md list-md list-inset&quot;]/ion-item-sliding[@class=&quot;md&quot;]/ion-item[@class=&quot;item-has-start-slot item md item-lines-default item-fill-none in-list ion-activatable ion-focusable item-label&quot;]/ion-label[@class=&quot;sc-ion-label-md-h sc-ion-label-md-s md&quot;]</value>
      <webElementGuid>ecae84d3-e761-41f0-9426-5c009e8471da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-router-outlet[@id='main-content']/div[3]/ion-content/div/div[2]/ion-list/ion-item-sliding/ion-item/ion-label</value>
      <webElementGuid>9b80d80e-f482-466e-a52a-9eb7c268797f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New Contact'])[1]/following::ion-label[1]</value>
      <webElementGuid>728da3b1-95b6-416f-93f8-4aef9a2fb62d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacts'])[1]/following::ion-label[2]</value>
      <webElementGuid>180bf214-fa2f-4efc-82e6-e9464e3e5020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='João Tavares'])[1]/preceding::ion-label[1]</value>
      <webElementGuid>b2420100-34ee-41ba-85ea-c37a8208ac73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-item-sliding/ion-item/ion-label</value>
      <webElementGuid>3099cf64-5ec3-411e-97e3-1eba27310034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-label[(text() = 'Afonso Cancela918821097' or . = 'Afonso Cancela918821097')]</value>
      <webElementGuid>3a2d5dc2-c16c-4029-9e5b-ecc1fb775ba3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
