<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-text_Phone number must be a valid Portuguese mobile phone number</name>
   <tag></tag>
   <elementGuidId>3278baf6-7db4-47b9-82ba-fe09dd504acd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ion-text.ion-color.ion-color-danger.md</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ion-modal[@id='ion-overlay-2']/div/ion-content/div/ion-grid/ion-row/ion-col/ion-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-text</value>
      <webElementGuid>8768b4e6-6979-4366-91eb-527c46938977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ion-color ion-color-danger md</value>
      <webElementGuid>8c8e385a-3719-4547-bd83-4a934619d7b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>danger</value>
      <webElementGuid>c47e25d0-1b46-4594-9fe9-20ab458b8f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Phone number must be a valid Portuguese mobile phone number</value>
      <webElementGuid>8fac4c01-f144-42a4-858c-8d10446cd545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ion-overlay-2&quot;)/div[@class=&quot;ion-page&quot;]/ion-content[@class=&quot;ion-padding md content-ltr&quot;]/div[@class=&quot;d-flex flex-column justify-content-space-between h-100&quot;]/ion-grid[@class=&quot;md&quot;]/ion-row[@class=&quot;md&quot;]/ion-col[@class=&quot;md&quot;]/ion-text[@class=&quot;ion-color ion-color-danger md&quot;]</value>
      <webElementGuid>9413f279-e2d1-4609-a731-ebabb236f636</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-modal[@id='ion-overlay-2']/div/ion-content/div/ion-grid/ion-row/ion-col/ion-text</value>
      <webElementGuid>ff558350-876d-41f9-b0f6-14676aaa7b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[1]/following::ion-text[1]</value>
      <webElementGuid>fe119973-0f56-4a50-8e3f-2c2e129428d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New Contact'])[2]/following::ion-text[1]</value>
      <webElementGuid>2867627c-1f38-4101-b8b5-5280cc8090b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name (optional)'])[1]/preceding::ion-text[1]</value>
      <webElementGuid>ee81eb95-455f-4dc9-8f7d-db54c8fc7ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save contact in my contacts list'])[1]/preceding::ion-text[1]</value>
      <webElementGuid>7f5ab7cf-34b1-46f1-9a84-1368a47ff387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-text</value>
      <webElementGuid>2968547c-4c04-4711-8d55-3a045729871c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-text[(text() = 'Phone number must be a valid Portuguese mobile phone number' or . = 'Phone number must be a valid Portuguese mobile phone number')]</value>
      <webElementGuid>e4a4ed87-32b7-4f11-845d-bad254236d17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
