<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_checkbox-icon-ts list-816</name>
   <tag></tag>
   <elementGuidId>325c8bd6-9bda-45bf-90ba-9669c1b2b164</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.checkbox-wrapper > div.native-wrapper > svg.checkbox-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>18b9cc5e-dd67-4098-b33b-25e7d6c9a911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-icon</value>
      <webElementGuid>f9b47d53-5489-409d-bdcf-46cb7bb01d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>ee8b0626-e8bf-4989-a6af-86dabe0ab03f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>container</value>
      <webElementGuid>736e24ee-f3a9-4645-92c4-7dd265f41e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/label[@class=&quot;checkbox-wrapper&quot;]/div[@class=&quot;native-wrapper&quot;]/svg[@class=&quot;checkbox-icon&quot;]</value>
      <webElementGuid>2fd47af9-9a65-4a73-979b-b638c9d1e87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>393cfbbd-c473-41d1-8f04-49a6e6778eb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>6b11e0c9-8c63-4c11-8aa6-51df1a678871</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
