<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-text_The confirmation code is incorrect</name>
   <tag></tag>
   <elementGuidId>02e0ccad-c502-4445-8922-e1e5fd62cec2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ion-modal[@id='ion-overlay-2']/div/ion-content/ion-grid/ion-row/div[2]/ion-text</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ion-text.ion-color.ion-color-danger.md</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-text</value>
      <webElementGuid>f8e1c6d3-f590-4b05-821b-46a31c7e03c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ion-color ion-color-danger md</value>
      <webElementGuid>366d9652-f38f-471c-af7f-08170e7ed5ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>danger</value>
      <webElementGuid>7cfa3085-6eb9-4d86-ba16-c51c57d54852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The confirmation code is incorrect</value>
      <webElementGuid>9eb57b43-969c-4f2b-a62b-2101cccc1912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ion-overlay-2&quot;)/div[@class=&quot;ion-delegate-host ion-page&quot;]/ion-content[@class=&quot;ion-text-center md content-ltr&quot;]/ion-grid[@class=&quot;vertically-center-aligned md&quot;]/ion-row[@class=&quot;md vertically-center-aligned&quot;]/div[@class=&quot;w-100&quot;]/ion-text[@class=&quot;ion-color ion-color-danger md&quot;]</value>
      <webElementGuid>c8b52e22-f993-4227-bb03-a6c3fde89a23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-modal[@id='ion-overlay-2']/div/ion-content/ion-grid/ion-row/div[2]/ion-text</value>
      <webElementGuid>b1344448-97c6-4c71-a806-2c87b04a1e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation Code'])[1]/following::ion-text[1]</value>
      <webElementGuid>d2217d90-88a8-48f1-93cd-49b21a5f8213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send'])[1]/following::ion-text[1]</value>
      <webElementGuid>b67f9e2b-ed92-4a48-8e9c-2acd324f54eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[1]/preceding::ion-text[1]</value>
      <webElementGuid>8bacdbc5-b13d-49b3-b1b5-dca1ab737426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::ion-text[1]</value>
      <webElementGuid>fd4695a6-1116-406e-9a64-e57954c6058d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ion-text</value>
      <webElementGuid>5abd04f2-3e74-411e-a338-5f71bedf3e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-text[(text() = 'The confirmation code is incorrect' or . = 'The confirmation code is incorrect')]</value>
      <webElementGuid>3e88ad37-dd97-418d-a56b-a44ca3fd9222</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
