<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-button_Filters</name>
   <tag></tag>
   <elementGuidId>91d31cbf-e1d1-427b-beaf-a3be8fda50b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ion-router-outlet[@id='main-content']/div[3]/ion-content/div/div/div/div/ion-button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ion-button.custom-button-filters.md.button.button-block.button-solid.ion-activatable.ion-focusable.ion-activated</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-button</value>
      <webElementGuid>a7955a71-f514-48b1-9b8d-dde704c601e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-button-filters md button button-block button-solid ion-activatable ion-focusable ion-activated</value>
      <webElementGuid>36c3123b-96e6-46e8-b6f7-813805e21aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>expand</name>
      <type>Main</type>
      <value>block</value>
      <webElementGuid>973dd7e9-51b4-44ec-b225-fc83dfb46f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>solid</value>
      <webElementGuid>76eac780-feb8-4b11-9622-70786200f138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Filters </value>
      <webElementGuid>52e78afa-540c-4250-803a-eb7578aa2511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ion-page can-go-back&quot;]/ion-content[@class=&quot;md content-ltr ion-padding&quot;]/div[1]/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;filters&quot;]/ion-button[@class=&quot;custom-button-filters md button button-block button-solid ion-activatable ion-focusable ion-activated&quot;]</value>
      <webElementGuid>f5bfe02d-b36e-4e39-91a2-425a27ca92fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-router-outlet[@id='main-content']/div[3]/ion-content/div/div/div/div/ion-button</value>
      <webElementGuid>bde8dd1a-7729-49f4-b163-b32d7eaf623e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transactions'])[1]/following::ion-button[1]</value>
      <webElementGuid>20899ce3-1216-465d-9d74-cb00c26b22c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show More'])[1]/following::ion-button[1]</value>
      <webElementGuid>cd6334ed-9a89-49ed-a8d5-ebd816004935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT96208402479312057159036'])[1]/preceding::ion-button[4]</value>
      <webElementGuid>6c9aeb7f-e712-4b98-a6f9-6f9d981681b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT24797555344792347442334'])[1]/preceding::ion-button[4]</value>
      <webElementGuid>d6ddde4b-fcf9-490a-b6d5-f473806725ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ion-button</value>
      <webElementGuid>14e9046e-cdbe-4473-9c60-a1b10b943b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-button[(text() = ' Filters ' or . = ' Filters ')]</value>
      <webElementGuid>b21bc3a2-c2ae-4a7a-abe4-5e6104ea6af7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
