<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-select_AllDebitCredit</name>
   <tag></tag>
   <elementGuidId>954ca0ce-523b-4a74-94e8-8d824d8dd407</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ion-modal[@id='ion-overlay-2']/div/ion-content/ion-list/ion-item/ion-select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ion-select.md.in-item.has-value.has-placeholder.ion-focusable.select-ltr.select-justify-space-between.select-label-placement-start</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-select</value>
      <webElementGuid>50eaa288-085a-466a-8d78-90b37cbef937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md in-item has-value has-placeholder ion-focusable select-ltr select-justify-space-between select-label-placement-start</value>
      <webElementGuid>4cc9f8f3-0fd9-438c-88fe-5606818faabe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>modelvalue</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>768a360e-9ad8-4c4a-ae1a-d4ad2361bcad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AllDebitCredit</value>
      <webElementGuid>d6ece2ab-d908-49d2-ae5c-3ea3e00f2462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ion-overlay-2&quot;)/div[@class=&quot;ion-page&quot;]/ion-content[@class=&quot;ion-padding md content-ltr&quot;]/ion-list[@class=&quot;md list-md&quot;]/ion-item[@class=&quot;item md item-lines-default item-fill-none item-has-interactive-control in-list ion-activatable ion-focusable ion-activated&quot;]/ion-select[@class=&quot;md in-item has-value has-placeholder ion-focusable select-ltr select-justify-space-between select-label-placement-start&quot;]</value>
      <webElementGuid>7f242a8a-ac25-4c2d-be5f-ddee91a8ea64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-modal[@id='ion-overlay-2']/div/ion-content/ion-list/ion-item/ion-select</value>
      <webElementGuid>0d42632a-8fee-48ec-8459-29cb489d7e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Date:'])[1]/following::ion-select[1]</value>
      <webElementGuid>b970e886-8b71-4303-ab07-cfcae8c9dbe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Date:'])[1]/following::ion-select[1]</value>
      <webElementGuid>32604e30-c9ef-43ce-9d89-bb68632daaeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-select</value>
      <webElementGuid>570bf494-c852-4081-addc-f0ee71b21b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-select[(text() = 'AllDebitCredit' or . = 'AllDebitCredit')]</value>
      <webElementGuid>c6dd9f09-ec44-474e-a2a0-292b8ecdf791</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
