<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-radio_Debit</name>
   <tag></tag>
   <elementGuidId>3501ad05-90ab-469d-bbc3-b932601fdcf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ion-item.select-interface-option.md.sc-ion-select-popover-md.item.item-lines-default.item-fill-none.item-has-interactive-control.ion-activatable.ion-focusable.ion-activated > ion-radio.sc-ion-select-popover-md.md.in-item.radio-justify-space-between.radio-alignment-center.radio-label-placement-start</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ion-popover[@id='ion-overlay-3']/div/ion-select-popover/ion-list/ion-radio-group/ion-item[2]/ion-radio</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-radio</value>
      <webElementGuid>4acaa8a6-b56b-4aca-a025-5c4752e2efb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-ion-select-popover-md md in-item radio-justify-space-between radio-alignment-center radio-label-placement-start</value>
      <webElementGuid>56184956-09b2-4549-8f1b-1bfc415c7c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>3cf5d248-37a3-48b8-8985-446f1f202106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b5c91ae1-916c-43ad-8125-19cb63cc5810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>26ded006-0e94-48cb-bc97-84eaf6144b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Debit</value>
      <webElementGuid>f7eb2f9d-48d4-46ce-b9bd-0b4916471489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ion-overlay-3&quot;)/div[@class=&quot;popover-viewport&quot;]/ion-select-popover[@class=&quot;sc-ion-select-popover-md-h sc-ion-select-popover-md-s md&quot;]/ion-list[@class=&quot;sc-ion-select-popover-md md list-md&quot;]/ion-radio-group[@class=&quot;sc-ion-select-popover-md md&quot;]/ion-item[@class=&quot;select-interface-option md sc-ion-select-popover-md item item-lines-default item-fill-none item-has-interactive-control ion-activatable ion-focusable ion-activated&quot;]/ion-radio[@class=&quot;sc-ion-select-popover-md md in-item radio-justify-space-between radio-alignment-center radio-label-placement-start&quot;]</value>
      <webElementGuid>b4e43b47-67f1-45bd-8e83-76510074d072</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-popover[@id='ion-overlay-3']/div/ion-select-popover/ion-list/ion-radio-group/ion-item[2]/ion-radio</value>
      <webElementGuid>f2c00740-646d-4277-9433-cfc08c533920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[2]/following::ion-radio[1]</value>
      <webElementGuid>55b047f5-40c6-43ae-8147-c84547e64d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit'])[1]/following::ion-radio[2]</value>
      <webElementGuid>0d2e8821-bddc-4cc9-827d-bd89f5bddb74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit'])[2]/preceding::ion-radio[1]</value>
      <webElementGuid>1b4d0a63-593c-43ef-b5c5-fe86241ce60e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-item[2]/ion-radio</value>
      <webElementGuid>687491d3-f074-44da-b7ac-226761d23801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-radio[(text() = 'Debit' or . = 'Debit')]</value>
      <webElementGuid>7ba7e19c-be37-43ee-a4f9-65d658b22808</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
