<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_dashboard</name>
   <tag></tag>
   <elementGuidId>a2162472-7aea-46c4-b3e2-70de22178acf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ion-router-outlet[@id='main-content']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ion-page.can-go-back</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a77ee924-ffec-4d17-8928-493f95235fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ion-page can-go-back</value>
      <webElementGuid>c03288b5-3236-47e4-a40b-56edbb9e8c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> dashboard </value>
      <webElementGuid>7e225b51-4eff-4ed9-a682-f01822cadf2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ion-page can-go-back&quot;]</value>
      <webElementGuid>e42bccad-e7e3-49bc-9846-1125c9f2adef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-router-outlet[@id='main-content']/div[2]</value>
      <webElementGuid>0ca348f0-9cdc-4542-88e5-fd105453539a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create'])[1]/following::div[1]</value>
      <webElementGuid>6d8a6a2f-31d9-41db-aff6-bcad17d5e439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PIN'])[1]/following::div[2]</value>
      <webElementGuid>617dc91e-b452-48db-aa32-36cb9d112d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'main-content', '&quot;', ')/div[@class=', '&quot;', 'ion-page can-go-back', '&quot;', ']')])[1]/preceding::div[1]</value>
      <webElementGuid>1e4eb6e2-e0a1-4095-9df1-b80284552d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='dashboard']/parent::*</value>
      <webElementGuid>e7c0c7b5-d5ca-4a91-8956-a24f2623bc49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-router-outlet/div[2]</value>
      <webElementGuid>c5de39bd-a7c1-43bd-9b52-c5a63c99b2a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' dashboard ' or . = ' dashboard ')]</value>
      <webElementGuid>e2c87779-31ac-44fe-b174-a619085ae8ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
