<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_piggy_bank_balance</name>
   <tag></tag>
   <elementGuidId>32ff2b6d-52fc-4e84-83db-30aa7b9a1373</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.container > div > h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ion-router-outlet[@id='main-content']/div[2]/ion-content/div/div/div/div[2]/ion-grid/ion-row/ion-col/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>0b799ed7-b732-4bed-bb2b-ed4d2e2d8c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No balance</value>
      <webElementGuid>64afb9c2-0cf6-4c34-b948-6179d22cffc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ion-page can-go-back&quot;]/ion-content[@class=&quot;md content-ltr&quot;]/div[1]/div[1]/div[@class=&quot;container-init&quot;]/div[@class=&quot;piggy&quot;]/ion-grid[@class=&quot;md&quot;]/ion-row[@class=&quot;md&quot;]/ion-col[@class=&quot;md&quot;]/div[@class=&quot;container&quot;]/div[1]/h1[1]</value>
      <webElementGuid>191a9067-3abb-4d4a-b162-0be4194a1a99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-router-outlet[@id='main-content']/div[2]/ion-content/div/div/div/div[2]/ion-grid/ion-row/ion-col/div/div/h1</value>
      <webElementGuid>7649aec8-988e-4ae8-a1f5-a01da05a62bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Piggy Bank'])[1]/following::h1[1]</value>
      <webElementGuid>b8c5b49a-83a8-4820-beb8-4d7aa3046442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No funds'])[1]/following::h1[1]</value>
      <webElementGuid>1da99738-b77c-48cb-8304-c33632fb0dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transactions'])[1]/preceding::h1[1]</value>
      <webElementGuid>0a55d47c-31ea-47c3-8fc4-f92600a3cb37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Transaction:'])[1]/preceding::h1[1]</value>
      <webElementGuid>a91eeac0-8ab8-4c80-877d-1e1a3866fef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-row/ion-col/div/div/h1</value>
      <webElementGuid>8946350d-0364-4456-93a1-6a149036581f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
