<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-button_Create (4)</name>
   <tag></tag>
   <elementGuidId>55a27356-b578-4955-a36f-e58deb59850d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ion-button.md.button.button-block.button-solid.ion-activatable.ion-focusable.ion-activated</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ion-router-outlet[@id='main-content']/div/ion-content/div/ion-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-button</value>
      <webElementGuid>e9eb6463-9044-4de6-826e-bdef4a269900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md button button-block button-solid ion-activatable ion-focusable ion-activated</value>
      <webElementGuid>03892d5c-975b-47ab-9000-38942b482ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>expand</name>
      <type>Main</type>
      <value>block</value>
      <webElementGuid>5a11949a-cb9e-46c5-bc4a-f7cf928eb5e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>7dd33a88-858c-43d5-a5f7-0b8e382a4000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ion-page&quot;]/ion-content[@class=&quot;ion-padding md content-ltr&quot;]/div[@class=&quot;container&quot;]/ion-button[@class=&quot;md button button-block button-solid ion-activatable ion-focusable ion-activated&quot;]</value>
      <webElementGuid>4c7c803b-ac24-4695-ab79-4ebc8fb9a4ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ion-router-outlet[@id='main-content']/div/ion-content/div/ion-button</value>
      <webElementGuid>f0574ebc-4e62-4e1f-9e8f-431eff807e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PIN'])[1]/following::ion-button[1]</value>
      <webElementGuid>7b823648-6ef6-4d05-896c-5f28a29fab8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::ion-button[1]</value>
      <webElementGuid>10b25f14-6dea-4d3c-93dc-5ad4c03a9f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create']/parent::*</value>
      <webElementGuid>a51f2958-2c81-4efa-a290-2a10693aa2a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-button</value>
      <webElementGuid>d747409e-e933-4998-9a98-37fd9cdfa453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-button[(text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>c15d77d1-c6d5-4beb-af0c-1ed04cac0d79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
