<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>slot-_268,10-0f9</name>
   <tag></tag>
   <elementGuidId>7326a0d8-78d0-4ab5-963b-178f06d50eaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>slot</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>slot</value>
      <webElementGuid>726f964d-69b1-4ac4-a55f-3eb06c555f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/slot[1]</value>
      <webElementGuid>1696d51c-508b-4af8-9970-e7e617ed8c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4ce0b3f5-cd80-47ab-952c-1dafb09a44d5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
