<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_button-inner-n_Enter-e91</name>
   <tag></tag>
   <elementGuidId>c20765ae-9714-496c-b9fa-aca946cb24d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button-native > span.button-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>78aeec51-dea4-4a3d-ac77-056507fe6efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-inner</value>
      <webElementGuid>e89cb7c2-9d79-48e6-817e-3b4d2f0d796a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/button[@class=&quot;button-native&quot;]/span[@class=&quot;button-inner&quot;]</value>
      <webElementGuid>a1929756-fdd0-47a2-b488-849c323a0307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Ionic App/ion-button_Enter (2)</value>
      <webElementGuid>48da8627-4a79-480f-b3dc-56a5553b6c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cf7e0c37-f269-4898-a5f6-fa8f4a2a199c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>49bf0a90-f1d1-4e65-8bdb-b365d567d751</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
